### ISSUE TITLE
User can drag/drop from NSOpenPanel

### ISSUE THREAD

**Issue by dxdc** [sveinbjornt/Platypus#102]
If settings are selected to allow NSOpenPanel to accept files on startup, user can drag/drop files from NSOpenPanel into the actual application which also accepts drag/drop files. This causes a bad user experience, since user can see files processing in background but no output is buffered to stdout until the entire process finishes.

My suggestion would be to open NSOpenPanel as modal to prevent this behavior.

https://www.dropbox.com/s/vdsovruo661dvsq/demo.mov?dl=1

**Comment by dxdc** [comment]
Attached video above.

**Comment by sveinbjornt** [comment]
Now fixed in master.
