### ISSUE TITLE
how to run a cleanup function before exiting

### ISSUE THREAD

**Issue by yyz1989** [sveinbjornt/Platypus#103]
Hi all,

I created an application with Status Menu interface and now looking for a way to do some cleanup work before exiting the application. It looks like by default there is always one item created for exiting named "Quit something". I have not found a way to hook to that item, so I also created one item called "Quit something" which can trigger my cleanup functions. Then I end up with two items both used for quiting, which does not look nice.

Does anyone know how to inject a clean up function into the default quit? Alternatively, it would also be great if we can simply remove the default quit from the menu.

Thanks a lot for any hint.

Best regards,
Yang

**Comment by sveinbjornt** [comment]
Currently, the script is only run in the Status Menu interface when the menu is opened. There is no way to hook into when the application quits. It's necessary to have a "Quit AppName" menu item at the bottom, because otherwise there would be no way graphical way to quit the app.

**Comment by yyz1989** [comment]
Hi Sveinbjorn, 

Thanks a lot for your quick response! 

Currently what I am doing is to produce another "Quit" item in the menu. If it is clicked, then some code will run to quit the actual application running behind the status menu, and then print "QUITAPP\n" to quit the status menu. It works quite good. I can understand the need of having a "Quit AppName" at the bottom, but as long as we can have a button in the status menu which does a similar job, then it is no longer mandatory. In the meanwhile, my naive guess is that as long as status menu can receive a "QUITAPP\n" to quit, it should also be able to receive another command which is executed before it processes "QUITAPP\n" request...

Best regards,
Yang

**Comment by sveinbjornt** [comment]
I've always equivocated about the right balance when it comes to Platypus: power vs. complexity. I've chosen to err on the side of simplicity with Platypus. It's unlikely that such hooks will be added in the future. But your point is well made and represents a legitimate use case.
