### ISSUE TITLE
run with root privileges with Status Menu interface

### ISSUE THREAD

**Issue by yyz1989** [sveinbjornt/Platypus#104]
Hi,

I created an application with Status Menu interface from my java Web application. I want the Tomcat server to start and listen to port 80, which requires root privilege. However, I discovered that when using "Status Menu" interface, "Run with root privilege" option is grayed out. It is available for all other types of interfaces, except Status Menu. However, in such a use case the Status Menu interface is the best option since it can be seen as a daemon service. What can I do here to request for root privilege?

Thanks a lot for any hint.

Best regards,
Yang

**Comment by sveinbjornt** [comment]
"Run with root privileges" is currently not supported for the Status Menu interface.
