### ISSUE TITLE
Version 5.2 is a problem, I do not see ffmpeg operation

### ISSUE THREAD

**Issue by Sergey-Galan** [sveinbjornt/Platypus#105]
Hello! I have Platypus Version 4.9 which perfectly works with ffmpeg. In a window there is a step by step display. Version 5.2 is a problem, I do not see ffmpeg operation, I see only result after operation.
On video Version 4.9 and Version 5.2 demonstration
It is possible to solve this problem?
https://youtu.be/P4eC1DdbY-c

**Comment by Sergey-Galan** [comment]
On video Version 4.9 and Version 5.2 demonstration

**Comment by sveinbjornt** [comment]
Probably related to the new output parser. I really should just implement support for carriage return.

**Comment by Sergey-Galan** [comment]
Thanks!

**Comment by Sergey-Galan** [comment]
You will correct this problem?
If you do not do it, I can receive Platypus Version 4.9 source codes?
Thanks!

**Comment by Sergey-Galan** [comment]
I cannot compile from Platypus Version 4.9 source codes
Such error. What do I do not so?
![2018-01-07 19 35 26](https://user-images.githubusercontent.com/30828202/34652090-4ead0c9c-f3e2-11e7-8052-58dd879b78aa.png)

**Comment by sveinbjornt** [comment]
I'll look into it but no promises. Platypus apps are not (and shouldn't be) full-fledged terminal clients, so support for stuff like carriage return is a very low priority.
