### ISSUE TITLE
Cannot open app - not supported on this Mac-type

### ISSUE THREAD

**Issue by kjetisve** [sveinbjornt/Platypus#108]
Hello,
I have created a little app using Platypus 5.2 which is working just fine on my mac (Macbook Air, macOS High Sierra 10.13.3, Intel).
When trying to run the app on a client's mac (Macbook Pro, macOS High Sierra 10.13.1, Intel) i am getting an error message, as well as a blocked sign on the app icon.

![screenshot 2018-02-08 10 03 51](https://user-images.githubusercontent.com/820577/35964234-64667cba-0cb7-11e8-8351-1200e7c72386.png)

**Comment by sveinbjornt** [comment]
Did you by any chance send the app via email without zipping it first?

**Comment by kjetisve** [comment]
Ah, cheers - that was probably it. I used Dropbox, and it got a .zip from it when I downloaded, but I had to manually zip it to get it to work. Sorry - don't know if this is the right place to get support, but thanks for replying. Great app!
