### ISSUE TITLE
Feature Request : Make Platypus a Document-based Application

### ISSUE THREAD

**Issue by DanErikPetersen-Serato** [sveinbjornt/Platypus#109]
# Feature Request

It'd be really nice if Platypus could be document-based, where configurations of generated apps would be stored in e.g. `*.platypus` files.

Opening a `*.platypus` file would then populate the main window with all the settings necessary to -re-generate the given app, and easily allow for tweaks to deployments.

Currently, the work-around to this is using e.g. the `platypus` CLI.

Would this feature be interesting/valuable?

**Comment by sveinbjornt** [comment]
I've actually thought about this in the past, but it would take a lot of work and a lot of new code, which I think would -- at least in short term -- introduce lots of new bugs in an application that has been working rather well for a very, very long time.

The decision to make Platypus a single-window app was made back in 2003, and I feel it would just break things to attempt a transition to the document model now.

**Comment by DanErikPetersen-Serato** [comment]
Understandable — and not a light change without risk.
