### ISSUE TITLE
Slow to show output when using drag and drop or "open with" ?

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#110]
Create an app that opens terminal and does a simple "Hello, World!" echo, the default script, then stays open. Make sure it can accept files by drag and drop and by file selector if none are passed on startup.

## problems
If I open the app and select a file, it displays the output instantly.

If I drag a file onto the app and select a file,   
OR  
If I select a file and use use Finder "open with",   
...there is a long (4–5 seconds) delay before the app shows the output window.

The app itself opens instantly, it's just the length of time between seeing the app menu and the window appearing.

## issue
Any ideas?

**Comment by sveinbjornt** [comment]
I'm unable to replicate this problem. 

However, it's worth noting that there is an important difference between opening files from the application's File menu and drag-n-dropping/doing Open With in Finder. The latter sends the application an Apple Event, whereas the former does not. Could something be interfering with the speed of AEvents on your system? Can you reproduce this on other Macs?

**Comment by gingerbeardman** [comment]
I'll try.

Here's a video: https://youtu.be/Omn0pHl7oQw

And here's my app: 
[app.zip](https://github.com/sveinbjornt/Platypus/files/1829906/app.zip)

**Comment by sveinbjornt** [comment]
There's no delay when I try do the same on my system. Which OS version are you using? Are you using anti-virus software of any kind? Have you tried rebooting and trying again (maybe Launch Services has become confused)? What about on a different user accoutn?

**Comment by gingerbeardman** [comment]
Interesting.

- 10.13.3
- No antivirus

Reboot = same
New user = no delay!

Any more thoughts welcome.

Will investigate.

**Comment by gingerbeardman** [comment]
So if I rebuild the app, making sure to check "Run in background", then there is no delay!

I see that options sets `LSUIElement` to be `TRUE`

Why would there be a delay only on my user account and only on apps with `LSUIElement` is `FALSE`?

**Comment by sveinbjornt** [comment]
This is very strange. I have no idea what could be causing this. My best guess is that you have some third party software enabled on your user account which is interfering with how Launch Services work.

**Comment by gingerbeardman** [comment]
I hope you don't mind me trying to figure this out here? 

I zapped all my preferences, launch agents, launch daemons, startup items and anything else that runs automatically in my account. Restart and login... Same delay. 

I then tried rebooting info safe mode - same delay. 

Interestingly, if I quit all unnecessary processes with `kill -3 -1` and then - as soon as the desktop reappears - quickly drag an item onto the app, it opens instantly. No delay. 

A few seconds later, trying again, and the delay is there again. 

I'm going to try to (manually) binary search through the running processes to figure out which one is responsible for the delay.

**Comment by gingerbeardman** [comment]
running a debug build of ScriptExec: everything is done in half a second!

the window appears 4 seconds after "task finished".

```log
default	18:11:38.706102 +0000	launchservicesd	CHECKIN:0x0-0x5c05c 949 com.gingerbeardman.Hash
default	18:11:38.797173 +0000	Hash	0x10549d000 - DocumentLoader::startLoadingMainResource: Returning empty document (frame = 0x1054c6280, main = 1)
default	18:11:38.797300 +0000	Hash	Memory usage info dump at MainFrameLoadCompleted:
default	18:11:38.797339 +0000	Hash	  pagecache_page_count: 0
default	18:11:38.797375 +0000	Hash	  compressed: 0
default	18:11:38.797409 +0000	Hash	  internal: 5500928
default	18:11:38.797444 +0000	Hash	  javascript_gc_heap_extra_memory_size: 0
default	18:11:38.797477 +0000	Hash	  virtual_size: 5541888000
default	18:11:38.797510 +0000	Hash	  document_count: 1
default	18:11:38.797542 +0000	Hash	  javascript_gc_heap_capacity: 32768
default	18:11:38.797573 +0000	Hash	  resident_size: 18718720
default	18:11:38.797603 +0000	Hash	  phys_footprint: 5496832
default	18:11:38.797931 +0000	Hash	0x7fcf4fc09ca0 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 70.0% CPU in state: VisibleNonActive
default	18:11:38.978422 +0000	Hash	Received openFiles event for files: (
    "/Users/matt/Desktop/enable_all_animation.sh"
)
default	18:11:38.979386 +0000	Hash	Application did finish launching
default	18:11:38.982172 +0000	Hash	Running task
/bin/sh '/Applications/Hash.app/Contents/Resources/script' '/Users/matt/Desktop/enable_all_animation.sh'
default	18:11:38.996454 +0000	Hash	Output:/Users/matt/Desktop/enable_all_animation.sh
 
MD5:
default	18:11:39.018135 +0000	Hash	Output:E8A662ABD450C45CD6A092F051D53884
error	18:11:39.020999 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.022128 +0000	Hash	Output:SHA1:
default	18:11:39.022402 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.024704 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.025094 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.026661 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.027146 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.030529 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.032278 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.035130 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.037117 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.040325 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.041326 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.043179 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.044283 +0000	Hash	[WARNING] could not find container for id: <private>
error	18:11:39.047188 +0000	Hash	[ERROR] Failed getting container for URL: <private>, error: <private>
default	18:11:39.049020 +0000	Hash	[WARNING] could not find container for id: <private>
default	18:11:39.050663 +0000	Hash	Failed to resolve bookmark 7fcf4fc2cd90 with error: <private>
default	18:11:39.051580 +0000	Hash	Failed to resolve bookmark 7fcf5002d200 with error: <private>
default	18:11:39.051642 +0000	Hash	Failed to resolve bookmark 7fcf5009dc00 with error: <private>
default	18:11:39.052130 +0000	Hash	Failed to resolve bookmark 7fcf50045a00 with error: <private>
default	18:11:39.053585 +0000	Hash	Failed to resolve bookmark 7fcf50033000 with error: <private>
default	18:11:39.055242 +0000	Hash	Failed to resolve bookmark 7fcf50044200 with error: <private>
default	18:11:39.056922 +0000	Hash	Failed to resolve bookmark 7fcf50010a00 with error: <private>
default	18:11:39.104360 +0000	Hash	Output:C202524589BAC9E0EB8401BE2BB9768FFBA7793C
default	18:11:39.106449 +0000	Hash	Output:SHA256:
default	18:11:39.150126 +0000	Hash	Output:756114C14CE8CC9FEA2A7519ADC39D260C5CFC5608C99BDC0C0E3C0D9B8ED976
default	18:11:39.151743 +0000	Hash	Output:CRC32:
default	18:11:39.239412 +0000	Hash	Output:ED210721
default	18:11:39.240045 +0000	Hash	Task finished
default	18:11:39.240835 +0000	Hash	Output empty
```

**Comment by sveinbjornt** [comment]
Might be related to the iCloud crap Apple's been pushing deeper into macOS. Have you tried disabling iCloud?

**Comment by gingerbeardman** [comment]
I've tried disabling iCloud, the issue remains.

At this point, I am considering a reinstall of macOS and if that still doesn't help then a complete setup and restore from backup.

**Comment by sveinbjornt** [comment]
Yeah, there's dinfitely something wrong with your system. I'd do the same. Anyway, I'm closing this issue. I don't think it's Platypus-related.

**Comment by gingerbeardman** [comment]
Agreed. Thanks for hearing me out!

**Comment by gingerbeardman** [comment]
OK, here's an update as I'd like your thoughts:

1. Carbon Copy Clone and restore - problem still present
2. Format drive, reinstall macOS, migrate from backup - problem still present

During further investigation, I created another new app as in the OP, with a different unique identifier:
1. first run: window appears instantly
2. second run: delay before window appears

If I try to uninstall that app with AppCleaner, then i can see what files are associated with it:

![screen shot 2018-03-29 at 22 51 18](https://user-images.githubusercontent.com/49612/38116138-bfab1ba6-33a6-11e8-9a4f-c52e6d289e68.png)

If I delete the _Saved Application State_ for the app, then on the next launch the window appears instantly. However, a subsequent launch of the app (with a newly regenerated saved application state) once again sees the long delay before the window appears.

If I look inside the SAS I see four files:
- data.data
- window_1.data
- window_2.data
- windows.plist

If I remove the file `data.data` then the delay goes away, but that file is regenerated when the app is quit. You can read about the encrypted contents of these files [here](https://reverseengineering.stackexchange.com/questions/9426/how-to-read-nscr1000-data-files).

Actually, there is a fifth file in the _Saved Application State_, but it is only present for - somewhat interestingly - the exact length of time there it takes for the window to appear (so not very long on first launch; and for a while on subsequent launches):
- restorecount.plist

The contents of which are:
![screen shot 2018-03-29 at 23 24 34](https://user-images.githubusercontent.com/49612/38116522-5e3ca4b4-33a8-11e8-8b9c-8f4e29cc3e90.png)

Any thoughts?

What could be causing the delay in processing the _Saved Application State_? A macOS bug?

**Comment by gingerbeardman** [comment]
Workaround: I can prevent the "Saved Application State" on a per-app basis, using:

`defaults write com.gingerbeardman.Test2 NSQuitAlwaysKeepsWindows -bool false`

I'm not sure if this should be an option in Platypus, or if I'm seeing a a bug in macOS, but that'll do me for now.

[ref](https://apple.stackexchange.com/questions/177428/how-to-prevent-one-app-from-saving-restoring-any-saved-state)

**Comment by gingerbeardman** [comment]
Just heard back from Apple about this:

> Engineering has determined that your bug report (39378510) is a duplicate of 19293778 and will be closed. 

the number of radars has almost doubled since this bug was first filed!

**Comment by ArturKovacs** [comment]
Thank you @gingerbeardman for investigating this and reporting your findings here. It helped me.
