### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [sveinbjornt/Platypus#114]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by gingerbeardman** [comment]
Do you have a portfolio of work that you can show? Previous icon designs you have done?

**Comment by prohtex** [comment]
For what it's worth, I'm a big fan of the current icon scheme.

**Comment by sveinbjornt** [comment]
Thank you very much for for your generous offer but I think I'll stick with the current application/document icon scheme for now.

**Comment by gingerbeardman** [comment]
I came straight back here after seeing the new icon.

What happened!?

**Comment by prohtex** [comment]
Yeah... whoa. I stand by my previous enthusiasm for the “classic” icon.

**Comment by gingerbeardman** [comment]
I see in changes.txt

> For 5.3
>    * First facelift in a decade: New application icons created by Drífa Líftóra

**Comment by prohtex** [comment]
Well, she has great personal style, but I'm not sure she's going to give Susan Kare a run for her money

**Comment by gingerbeardman** [comment]
Echoing the above, the issue became obvious to me when it took quite a few seconds for me to figure out what the new icon was - a platypus. And this is knowing the application is called Platypus.

**Comment by prohtex** [comment]
Well it does look a bit like a spermazoidal banana. But you know, design is hard work, and someone did put their hard work into it. You can't please everybody all the time.. or in my case, really just about anyone, for more than a few weeks.

Maybe just a few tweaks to make them read better?

![icon_512x512 2x](https://user-images.githubusercontent.com/12946938/48986309-1dddca00-f0c8-11e8-9ee8-fba9ed384b8a.png)
![platypus](https://user-images.githubusercontent.com/12946938/48986313-2afab900-f0c8-11e8-9a15-4d5171e59283.png)

**Comment by prohtex** [comment]
The banner headline here should be that 5.3 is out.. early, a very welcome development. THANK YOU Sveinbjorn!

**Comment by sveinbjornt** [comment]
Hey guys, I'm flattered that you take such a keen interest in the new icon for this old piece of software!

The decision to change the icons and stop using Jon Hooper's Hexley (the Darwin mascot) was not made lightly. The icons looked increasingly dated after the aesthetic changes in recent versions of macOS, where skeumorphism, depth and strong shadows are out of place. A young designer I know personally offered to make a new one for me, more in keeping with the direction Mac applications are going. I'm quite happy with the outcome and I'm sorry to hear not everyone feels the same.

For my part, I think they look considerably better than the old ones at smaller sizes and in Mojave's Dark Mode (see attached screenshots). I also think Hexley never looked like much of a platypus in the first place -- more like Donald Duck. Never the less, I'll send your comments to the designer and hear what she thinks. 

That being said, people can use any icon they want for their Platypus-generated apps. I may even add a "Default Icon" option to the Preferences for the next versions. I even contemplated keeping the old default icon as an option.

![screenshot 2018-11-26 at 14 04 59](https://user-images.githubusercontent.com/654045/49033905-5bb21f80-f1a8-11e8-881e-d24807ef2f7d.png)
![screenshot 2018-11-26 at 14 05 03](https://user-images.githubusercontent.com/654045/49033907-5c4ab600-f1a8-11e8-8379-910756f3f6e6.png)
![screenshot 2018-11-26 at 14 05 21](https://user-images.githubusercontent.com/654045/49033908-5c4ab600-f1a8-11e8-80c9-bf5d646147b7.png)
![screenshot 2018-11-26 at 14 05 27](https://user-images.githubusercontent.com/654045/49033909-5c4ab600-f1a8-11e8-9a6a-3fc8095d2952.png)

**Comment by gingerbeardman** [comment]
Hi Sveinbjorn, thanks for the summary. I think we totally understand the direction, and actually i agree that it was overdue. However, the issue for me is the execution. I look forward to hearing what the designer says about this feedback.
