### ISSUE TITLE
Add a menu item to .nib

### ISSUE THREAD

**Issue by prohtex** [sveinbjornt/Platypus#117]
First, let me say a huge "thank you" to @sveinbjornt for all his hard work on this most excellent and versatile application. I've already used it to create a bunch of useful Mac apps and I'm blown away. Wow! Thank you!

I know the focus of Platypus is on simple script execution and not complex interaction, but I've put together a pretty good preferences window for my .app using Pashua, and was hoping to be able to invoke it somehow.

The ideal way to do this of course would be to add a "Preferences" menu item by editing the .nib file. I can add the menu item, but have no way to link it to any kind of action. I'm a complete Xcode novice and generally find it baffling. I've been able to link the menu item to a few predefined actions but that's about it.

<img width="1946" alt="screen shot 2018-08-11 at 7 53 50 am" src="https://user-images.githubusercontent.com/12946938/43993099-5ffd453e-9d3d-11e8-870f-7d22b2d1c408.png">

I have a script in my .app bundle that invokes the Pashua window--I just can't figure out how to link it to this menu item or to get it to launch from inside my Platypus app. I know there's a myriad of ways of gathering user input using AppleScript and other types of dialogs, but as the concept of preferences is not really a part of the app workflow, I was hoping for some sort of a solution. Re-running my main script with an argument, launching an external .app, launching a script, anything at all would allow me to open the prefs window.

Many thanks in advance for help/advice.

**Comment by prohtex** [comment]
I'm still hoping someone out there has made a Platypus app with a preferences window and might be able to point me in the right direction!

**Comment by sveinbjornt** [comment]
Something like Pashua might do the trick. Caveat: Haven't checked the state of that project in a while.

https://www.bluem.net/en/projects/pashua/

**Comment by sveinbjornt** [comment]
But you're not going to be able to hook into that Preferences menu item unlesss the ScriptExec binary and its assets are modified. How would the interaction with Platypus even work? A GUI window within Platypus where you can add modifiable preferences to the app? How would the Prefs window look? What kind of controls should be on offer? What kind of values? String, boolean, multiple choice? Complexity starts to scale quickly here.

That being said, you could always alter the ScriptExec binary according to your needs.

**Comment by prohtex** [comment]
I've tried, and in fact it does not (that project is also sort of in "open source doldrums"). The workaround is that I can use an external tool to detect a keypress on launch, and open a cocoaDialog window that way, but this only works on launch, and is far from elegant. I'm assuming there's no way to create a simple hook from that menu item to invoke a script or action? I really love Platypus and have been using it like crazy, but it would be a tremendous help to have any kind of method for invoking an additional script or app after the primary script has started running. I know this is not the paradigm, but for something like a preferences window I can't see another solution that would make sense.

**Comment by sveinbjornt** [comment]
I actually got a really good idea from thinking about this. What if I modify the ScriptExec binary to have a generic IBAction called menuItemSelected: or something, which isn't hooked to anything, but when called, runs the script with the menu item title (much like in Status Menu mode). Power users would then be able to add menu items in the nib and attach it to the menuItemSelected: action.

**Comment by prohtex** [comment]
Oh my god ... This is EXACTLY what I was hoping for!!

**Comment by prohtex** [comment]
I am over the moon! I'm not sure if I will be able to build Platypus from source though, as in the past I had an issue with developer code signing. I'm very sorry but I'm pretty bad with XCode (which is a bit of a catch-22 because if I could figure out I might actually make some native apps). I'm on 10.13.6 because Mojave introduced some new sandboxing stuff that broke many of my Platypus apps and I haven't had time to sort it out. If there is some way to work with a compiled app with the modification, I will dive into it tonight and let you know how it goes!

**Comment by sveinbjornt** [comment]
OK, just pushed this to master. You should be able to build Platypus without problem by just disabling code signing on the Platypus and platypus_clt targets. Then cd to the project directory, and run ./build_release.sh. Should do the trick. If you run into trouble, ping me and I'll send you binaries.

**Comment by prohtex** [comment]
I'm so sorry, but I wasn't able to get it to build.

<img width="804" alt="screen shot 2018-11-26 at 3 31 38 pm" src="https://user-images.githubusercontent.com/12946938/49048689-85f7e300-f190-11e8-83cf-12b4a371036a.png">
<img width="1055" alt="screen shot 2018-11-26 at 3 32 05 pm" src="https://user-images.githubusercontent.com/12946938/49048693-88f2d380-f190-11e8-8e66-4b0db20cf473.png">

**Comment by sveinbjornt** [comment]
Binaries here:
https://sveinbjorn.org/files/bin.zip

**Comment by prohtex** [comment]
Thanks and sorry I'm such an xcode dunce. I'll let you know how it goes!

**Comment by sveinbjornt** [comment]
No worries. This Apple signing business sucks, really clamps down the platform. I'm leaving soon, probably when my creaking 2012 rMBP kicks the bucket, Linux on generic x86 after that.

**Comment by prohtex** [comment]
Sorry to hear, and hope Platypus lives on for a long time to come. I've been able to create GUIs for a whole lot of Mac-specific software that folks typically run in a terminal window with the PHP cli, and it has been invaluable.

Yeah, Apple is not developer-friendly these days, esp where desktop software is concerned. This kind of stuff is driving me nuts:
https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave

It does seem like Ubuntu keeps getting more viable as a full service desktop OS, but there's always stuff I miss. At least with the 2018 Macbook Air there's finally a reasonable dev machine being manufactured again.

**Comment by prohtex** [comment]
Oh wow, I built a test app and it is truly glorious! So many thanks for this incredible addition! I'm going to push a bunch of updates to my Platypus apps and hopefully make some people very, very happy!

https://drive.google.com/open?id=1Zl-vrexu5ZN3NZWIa9Wu7MR9MBphU63z
