### ISSUE TITLE
Clear script output

### ISSUE THREAD

**Issue by prohtex** [sveinbjornt/Platypus#118]
I have a PHP script running in a Progress Bar window. At different intervals, I'd like to be able to clear the output of the "Details" pane, similar to what is mentioned in #96. I've tried echoing "REFRESH," as well as a number of standard PHP tricks found here:
https://stackoverflow.com/questions/4320081/clear-php-cli-output

If I turn on output buffering, I can suppress output, but I still can't clear what has already been output. What I'm looking for is a simple command I can echo to Platypus to cause the contents of the field displaying the script output to clear. Is that possible?

**Comment by sveinbjornt** [comment]
Hmmm... try printing "REFRESH\n" to STDOUT, should do the trick, at least with the latest version on the master branch.

**Comment by prohtex** [comment]
I tried that on 5.2 - do you mean I should try to build Platypus in xcode? I'm getting a code signing error but haven't really dug into it.

**Comment by cylott** [comment]
Is there a new release coming soon? I'd also like to be able to use REFRESH to clear the output but it doesn't seem to be working in 5.2.

**Comment by sveinbjornt** [comment]
I'm afraid it may be some time until 5.3 gets released. In the meantime, you can clone the Platypus master repo and build it yourself.
