### ISSUE TITLE
Default author name not respected

### ISSUE THREAD

**Issue by prohtex** [sveinbjornt/Platypus#119]
This preference doesn't work for me - the default author name on new Platypus projects is always the logged-in user.

<img width="445" alt="screen shot 2018-08-13 at 12 45 17 am" src="https://user-images.githubusercontent.com/12946938/44018971-5267d9ce-9e92-11e8-8205-4593e4ac33d0.png">

**Comment by sveinbjornt** [comment]
Fixed in master.
