### ISSUE TITLE
Keep window on top

### ISSUE THREAD

**Issue by prohtex** [sveinbjornt/Platypus#120]
Is there a way to make the main window in a Platypus .app retain focus or "stay on top"? I was hoping do to something like what this person is asking by editing the plist, but can't tell if it is possible:

https://stackoverflow.com/questions/19567781/force-keeping-app-window-on-top-mac-os-x

**Comment by sveinbjornt** [comment]
This can't be done by editing the plist, which only allows you to set LSUIElement to true, making the app a "background" app. Platypus-generated apps do not support keeping the window "on top" as you describe but this can be accomplished natively in Cocoa. Not a planned feature as it is a really marginal use case.
