### ISSUE TITLE
How can I use platypus to create a javafx app

### ISSUE THREAD

**Issue by wenerme** [sveinbjornt/Platypus#121]
I use shell like 

```sh
#!/bin/bash

cd "${0%/*}"
./jdk/bin/java -Xmx64m --upgrade-module-path ./ -m mymod
```
This works, but will open another window.

![image](https://user-images.githubusercontent.com/1777211/47446277-7f6ef800-d7ed-11e8-9de4-700f3d2a8370.png)

After I exit javafx application, the app not exit.

**Comment by sveinbjornt** [comment]
Java apps in macOS automatically register as their own "apps" as far as the OS is concerned, so you're stuck with an additional Dock icon unless you can find a way to suppress this behaviour.

As for quitting when the Java app quits, you can deselect "Remain running after execution". Then the Platypus application wrapper will quit once the script exits.
