### ISSUE TITLE
can launch a script that works on CLI to launch GUI app?

### ISSUE THREAD

**Issue by zeltak** [sveinbjornt/Platypus#122]
hi all

new to OSX so excuse the maybe trivial question. i read through the documentation and googled but cant really solve my issue.

I want to create another instance of a browser (qutebrowser) which will run with different arguments from the normal qutebrowser instance.

I created this script as a simple starting point

```
  Platypus cat /Users/zeltak/Library/Application\ Support/Platypus/qriver.sh
#!/bin/bash
/Applications/qutebrowser.app/Contents/MacOS/qutebrowser%
```
when i launch it from the CLI qutebrowser indeed comes up.

yet when i try to launch it as an `app' generated from platypus qutebrowser dosent seem to come up.

any idea how to try and debug this? is this a bug or missing knowledge (more likley :)) from my part?

best

Z

**Comment by sveinbjornt** [comment]
My guess is that your use case relies on some shell environment variables that (obviously) aren't defined when Platypus runs your script. Still interested in resolving this?

**Comment by zeltak** [comment]
Hi!

yeah im still interested. im a bit of a neewb and would love to debug this with some guidance

best

Z
