### ISSUE TITLE
Generated applications are not valid apps in eyes of Gatekeeper

### ISSUE THREAD

**Issue by scrod** [sveinbjornt/Platypus#124]
After code-signing a .app bundle generated by Platypus, ```spctl -a -t exec -vv``` results in the following error:
```rejected (the code is valid but does not seem to be an app)```

Adding a "CFBundlePackageType" key to Info.plist with a value of "APPL" resolves the problem.

**Comment by sveinbjornt** [comment]
Fixed in master.

**Comment by lilyball** [comment]
My friend just hit this issue. You should consider doing a new release in order to get this fix in.
