### ISSUE TITLE
Feature request: "Repeat Drop" button

### ISSUE THREAD

**Issue by gkholman** [sveinbjornt/Platypus#126]
In my environment I have a text window supporting drag and drop. Everything is working perfectly and I delight in using it.

While coding and especially when demoing, I find that I am repeatedly (sometimes dozens of times) dragging and dropping the same file or files onto the same text window.

What I would find very convenient next to the "Quit" button is a "Repeat" or "Repeat Drop" button that I can just click rather than taking the time to find the same file in Folder again and drag and drop it.

Yes, I realize I could have a script that simply invokes the same script that I've configured Platypus to do, but the demo gets better reception from some when I use the drag and drop (some people seem allergic to the Terminal window).

Thank you for considering this!

. . . . . Ken

**Comment by sveinbjornt** [comment]
This is a very specialised need and would not, to my mind, make a good addition to Platypus apps. However, thank you for your feedback and feature suggestion!

**Comment by gkholman** [comment]
Thank you for taking the time to consider this. Of course it is your prerogative not to include it, and I fully accept that.

Perhaps other users will champion this feature as well should they see the utility in it when reading the archives.

**Comment by gkholman** [comment]
If I could please resurrect this, I thought of a parallel in other programs that would provide for a keystroke to do what I am asking here, instead of a button.

The mouse way I can do what I want to do without using drag-and-drop a second time is to use the File/OpenRecent menu item and choose the top entry.

In Firefox there is a keystroke that opens the top entry of the RecentlyClosedTabs menu item, Command+Shift+T: https://blog.mozilla.org/theden/2012/07/26/shortcut-to-reopen-closed-tabs/

The same Command+Shift+T works in Chrome to open the most recently closed tab.

If you would consider supporting Command+Shift+T to re-open the most recent entry of File/OpenRecent, that would be a tremendous convenience to me. No buttons, no mess.

Thank you for thinking of this. . . . . . . Ken
