### ISSUE TITLE
MacOS Mojave default .Applescript editor stays set to Platypus

### ISSUE THREAD

**Issue by bikermikem** [sveinbjornt/Platypus#127]
After opening Platypus, the default editor for Applescripts was set to "Platypus".  After uninstalling Platypus and rebooting, the default editor is still Platypus.  This is when you right click on a Applescript file in the Finder and select "Open with..."

I also opened the file Info window for an Applescript and it shows "Script Editor" as default.  Changed it to another text editor (Vim) and set all .scpt files to be Vim and then changed it back to "Script Editor" but the "Open with" still shows Platypus.

**Comment by sveinbjornt** [comment]
Once you uninstall Platypus, the Finder should no longer show it in the Open With menu. If it does, there is some issue with your system. Might want to rebuild your Launch Services database:

https://www.tekrevue.com/tip/rebuild-launchservices-fix-duplicate-entries-os-xs-open-menu/

**Comment by bikermikem** [comment]
Thank you.
