### ISSUE TITLE
log file save

### ISSUE THREAD

**Issue by chris1111** [sveinbjornt/Platypus#128]
Please can you make an option to save log file automatically ( Exemple saving) to ➤ Desktop
Because when I use progreesbar with "QUITAPP" I can not save anything
Thanks for your great work

**Comment by sveinbjornt** [comment]
Why not just write the output to a file in the script itself? I don't think this use case is sufficiently generic.

**Comment by chris1111** [comment]
> Why not just write the output to a file in the script itself? I don't think this use case is sufficiently generic.

if I write Output in text file I do not have any output on the program
that's why I ask the question here

**Comment by chris1111** [comment]
maybe you have a correct way to do this ?
