### ISSUE TITLE
Custom icon is not displayed as expected when added to profile

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#129]
Original icon (reduced in size) PDF file
![icon-128](https://user-images.githubusercontent.com/49612/51432206-b35e8b80-1c2b-11e9-8650-edf7d55648db.png)

Platypus
![screen shot 2019-01-19 at 20 49 34](https://user-images.githubusercontent.com/49612/51432222-ea34a180-1c2b-11e9-8abd-dc2a62448b1d.png)

If I then use that screenshot PNG as an icon, Platypus looks like this:
![screen shot 2019-01-19 at 20 50 31](https://user-images.githubusercontent.com/49612/51432227-f7519080-1c2b-11e9-8e29-cb58bab2ca18.png)

**Comment by gingerbeardman** [comment]
ICNS works OK

**Comment by gingerbeardman** [comment]
Not really, Retina MBP but connected to Apple Cinema Display (Aluminium) which is not retina 1920x1200@1x

**Comment by sveinbjornt** [comment]
I am unable to reproduce this. Sounds like an IconFamily issue with 512x512@2x representations. Is ths still in master?

**Comment by gingerbeardman** [comment]
Yes, I just built master and it's still there.

**Comment by sveinbjornt** [comment]
Although I've not yet been able to reproduce this, I just changed image to icon generation in Platypus over to more modern code. Does this still happen using Platypus built from master?

**Comment by gingerbeardman** [comment]
Sadly I am away at the moment and won't be back to the monitor I normally use.

(it seems problem does not appear without the monitor)

**Comment by sveinbjornt** [comment]
I'm going to assume this is fixed, probably related to IconFamily's problems with handling of 512px icons.

**Comment by gingerbeardman** [comment]
I'll check this ASAP, we just had a baby and are not yet back home
