### ISSUE TITLE
Can't build 5.3 from source

### ISSUE THREAD

**Issue by chdiza** [sveinbjornt/Platypus#130]
I seem not to be able to build the platypus 5.3 CLT from source.  I always get this with plain `xcodebuild` in the terminal:
```
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "5WX26Y89JP" with a private key was found. (in target 'Platypus')

Build system information
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "5WX26Y89JP" with a private key was found. (in target 'platypus')

** BUILD FAILED **
```

I used to use  `xcodebuild -project Platypus.xcodeproj -target platypus -target ScriptExec`, but that results in the similar:
```
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "5WX26Y89JP" with a private key was found. (in target 'platypus')

** BUILD FAILED **
```
I hope we don't need a paid Apple Developer subscription to build platypus!  Is there a way to maybe make a special target or something that doesn't require signing?  Or at least that will accept a local self-signed cert?

(I also can't build it using Homebrew when I bump the version to 5.3.  They've still got 5.2.)

**Comment by sveinbjornt** [comment]
No paid account (or any account) required! I actually don't pay for a developer account myself. However, as of 5.2, Platypus.app and the platypus command line tool are signed using my free developer ID. To build Platypus, just turn off signing in the Xcode project. Nothing needs to be signed.

I'm also working on changing the customised build script to give more options, and remove the functionality tailored to my own, specific needs.

**Comment by sveinbjornt** [comment]
It's all set in the xcodeproj file, but maybe xcodebuild accepts some command line flags.

**Comment by sveinbjornt** [comment]
Looks like setting env CODE_SIGN_IDENTITY="" and CODE_SIGNING_REQUIRED=NO will do the trick. See:

https://stackoverflow.com/questions/11034133/building-ios-applications-using-xcodebuild-without-codesign

**Comment by chdiza** [comment]
Thanks, but none of that helped.  I guess I'll just use the Xcode GUI.
