### ISSUE TITLE
Attempting to sign code

### ISSUE THREAD

**Issue by Viss** [sveinbjornt/Platypus#131]
Hello!
 
Before creating this ticket I spent 3-4 days attempting to exhaust every possible option I could to sign apps created with platypus. 

This was the most detailed writeup I found: https://stackoverflow.com/questions/31709087/failure-digitally-signing-a-mac-app-outside-xcode

and I've found some others. I've tried every single thing I could find and I can't seem to get signed apps to behave properly. 

It has to do with gatekeeper, so far as I can tell. If I sign the app and just copy it around it seems to work, but if i post the app in a zip or a dmg I get an error saying "this developer cannot be identified", despite clearly having a signature when checked with codesign -dv --verbose=4.

That writeup I linked suggests that the binaries need to live in a special directory inside the app, and when including files (even binaries) using platypus, they go into the Resources dir, and the codesigning tools seem to complain about that, so in my testing I'm using the 'hello world' example shellscript to sort out what configuration actually works, and even that doesnt seem to make it past gatekeeper. 

Is there an approach for this on mojave? because it seems like apple has changed the rules after mojave.

**Comment by sveinbjornt** [comment]
I feel your pain but I'm afraid you're on your own, as I haven't bothered to learn much about how exactly code signing on macOS works. I have never paid Apple for a developer license and never will, and I think their policy on unsigned apps is grotesque and evil, part of a counterproductive strategy to clamp down on developers such as myself. There's a reason Platypus isn't available via that horrid App Store (ugh).

**Comment by vborodav** [comment]
Hi there!

I've found a solution for codesign. 
You just need to add new key to info.plist:
```
<key>CFBundlePackageType</key>  
<string>APPL</string>  
```

After that you will be able to run command:
`codesign --deep --force --verbose --sign "<identity>" path/to/Your.app`

Check codesign:
`spctl -a -vvvv  path/to/Your.app`
`codesign --verify -vvvv  path/to/Your.app`

Here is an original article:
https://forums.developer.apple.com/thread/77430

**Comment by sveinbjornt** [comment]
This issue is already fixed in master. Who'da thought the old Classic file type metadata was still being used for bundle identification!
