### ISSUE TITLE
Droplet accepting files and passing onto python script

### ISSUE THREAD

**Issue by rohithth** [sveinbjornt/Platypus#132]
Hi,

I'm really stuck up with this for a long time. I'd really appreciate your kind help!

I'd like to drop ".csv" file into droplet and then a python script will read the .csv file and do the typical pandas calculation and output the new .csv into the same directory.

Python script calculation is not an issue. But i don't know how to accept the file and then pass this as dataframe into python. I believe it has got to do with args but i'm really puzzled. If you could share a very simple app that accepts csv(A1 cell is 5, A2 cell is 4) and then adds two number from rows n throws csv output(A1 cell answer as 9) ,that would be great!!!

P.S. Existing example for droplet is a bit puzzling. A very simple use case of csv would be of great great help.

This will propell mass usage and adoption! Thanks a ton for your time!!
Really look forward to help.

**Comment by sveinbjornt** [comment]
The path of dropped files are passed as arguments to your script. If you're using Python, you can access them via sys.argv, e.g. (some pseudocode there, fill in the blanks):

    import sys
    csv_file_path = sys.argv[1]
    csv_data = readcsvfile(csv_file_path)
    new_csv_data = do_calculations(csv_data)
    ... write to new path

Parsing CSV is something that you do in the script itself and has nothing to do with the Platypus wrapper as such.
