### ISSUE TITLE
Chrome driver not working 

### ISSUE THREAD

**Issue by joeymeech** [sveinbjornt/Platypus#133]
I am using selenium and I can’t seem to get chrome driver working. I specified the path in my code and put the .app there and it didn’t work also I tried to bundle chrome driver with the .app and that also doesn’t seem to be working any fixes?

**Comment by sveinbjornt** [comment]
This is not really a Platypus question. My guess is that you need some environmental variables set. Platypus apps don't automatically inherit the user's shell environment. See "How does my script access the user's shell environment?" in the documentation for details.
