### ISSUE TITLE
Using a Perl version shipped with the .app

### ISSUE THREAD

**Issue by KellyOBrian** [sveinbjornt/Platypus#135]
I would like to adapt an application bundle created with Platypus (MyApp) to use a Perl installation contained in the .app itself. The reason: I need a different Perl than the macOS system one + custom installed modules.

I can set the Perl interpreter the .app should use modifying the AppSettings.plist (available in Resources of the .app). However, it seems I can only use full paths. I have the following values:

Key: InterpreterPath
Type: String
Value:   /Users/kb/Desktop/MyApp.app/Contents/Resources/perl5/perlbrew/perls/perl-5.26.1/bin/perl

Of course, the MyApp.app will not work if I move it around or if I use it on another computer. Is it possible to make the path relative to the MyApp.app location?

I tried to change value as follows:

Value: ./MyApp.app/Contents/Resources/perl5/perlbrew/perls/perl-5.26.1/bin/perl

I posted this issue in https://superuser.com/questions/1427329/use-relative-path-in-plist-made-with-platypus and I was suggested to ask here

**Comment by sveinbjornt** [comment]
Bundling an interpreter with the app and invoking it directly is on the feature list for Platypus 5.3. Meanwhile, you can get around this by using a shell script.

**Comment by cylott** [comment]
> I would like to adapt an application bundle created with Platypus (MyApp) to use a Perl installation contained in the .app itself. The reason: I need a different Perl than the macOS system one + custom installed modules.

https://github.com/sveinbjornt/Platypus/issues/146#issuecomment-539394666

**Comment by sveinbjornt** [comment]
Fixed in master. Interpreter path can now be relative (to the Resources directory of the application bundle), so a bundled interpreter can be referenced.
