### ISSUE TITLE
Dark Mode "Native" Color for Text Areas

### ISSUE THREAD

**Issue by prohtex** [sveinbjornt/Platypus#138]
I've noticed that text areas are not affected by Dark Mode, presumably because Platypus allows setting the background color of these areas manually. I'm wondering if there might be a way to specify a "native" text area color, to more fully support Dark Mode.

<img width="550" alt="Screen Shot 2019-05-22 at 6 03 44 PM" src="https://user-images.githubusercontent.com/12946938/58218602-526bc080-7cbc-11e9-8962-c453df39ec00.png">
<img width="692" alt="Screen Shot 2019-05-22 at 6 03 04 PM" src="https://user-images.githubusercontent.com/12946938/58218606-57307480-7cbc-11e9-84cb-295c265c13c4.png">

**Comment by chris1111** [comment]
simply choose text settings

![Capture d’écran, le 2019-06-14 à 13 08 37](https://user-images.githubusercontent.com/6248794/59525967-c2c5c600-8ea5-11e9-8596-30d23900b84e.png)

**Comment by sveinbjornt** [comment]
At the moment, there is no support for changing text foreground and background colors for dark mode. However, it might make sense add something like that in Platypus 5.4.

**Comment by chris1111** [comment]
Ha ok But its only in progress app because text window is not an issue

**Comment by prohtex** [comment]
> simply choose text settings
> 
> ![Capture d’écran, le 2019-06-14 à 13 08 37](https://user-images.githubusercontent.com/6248794/59525967-c2c5c600-8ea5-11e9-8596-30d23900b84e.png)

The issue is that the text settings are fixed. If you make them “dark,” they will always be “dark,” even if the user disables dark mode. We need a way to specify “use system default” as window color, so that it will change when the user enables/disables dark mode. Glad to hear it is on the horizon.

**Comment by Sergey-Galan** [comment]
I for myself solved a problem so:
`Themes_Dark()
{

MyApp="`pwd | rev | cut -d "/" -f3- | rev`"

if [[ "`defaults read -g AppleInterfaceStyle`" = Dark ]] && [[ `fgrep "#e6e6e6" ./AppSettings.plist` ]]; then
plutil -replace TextBackground -string "#3b444b" ./AppSettings.plist
plutil -replace TextForeground -string "#ffffff" ./AppSettings.plist
stop=$(ps aux|grep 'App'|grep -v grep|awk '{print $2}'); kill echo ''$stop'' & open "$MyApp"
elif [[ "`defaults read -g AppleInterfaceStyle`" != Dark ]] && [[ `fgrep "#3b444b" ./AppSettings.plist` ]]; then
plutil -replace TextBackground -string "#e6e6e6" ./AppSettings.plist
plutil -replace TextForeground -string "#000000" ./AppSettings.plist
stop=$(ps aux|grep 'App'|grep -v grep|awk '{print $2}'); kill echo ''$stop'' & open "$MyApp"
fi &> /dev/null

}`

**Comment by sveinbjornt** [comment]
I will take this very seriously under consideration for the next release of Platypus.

**Comment by sveinbjornt** [comment]
Fixed in master.

**Comment by Sergey-Galan** [comment]
![Снимок экрана 2021-06-25 в 00 04 46](https://user-images.githubusercontent.com/30828202/123332398-1cf3ca00-d549-11eb-9fb2-c69eedffd31f.png)
![Снимок экрана 2021-06-25 в 00 05 14](https://user-images.githubusercontent.com/30828202/123332418-23824180-d549-11eb-9347-355c7573f2cd.png)
Doesn't work, or am I doing something wrong?

**Comment by sveinbjornt** [comment]
Sure you got the latest version? Maybe you tried just before I pushed the changes.

**Comment by Sergey-Galan** [comment]
I downloaded once again. Now everything works! Thanks!
