### ISSUE TITLE
Progress bar with "start" button

### ISSUE THREAD

**Issue by cylott** [sveinbjornt/Platypus#140]
I'm wondering if it might be possible to create a Progress Bar app that doesn't "start" until a button is clicked. I have a script that does not accept dropped input, and simply needs to run when called and display a progress bar. Starting the script automatically on launch doesn't really make sense in my case. I would imagine the "Start" button would then change to "Cancel" while the script is running.

**Comment by chris1111** [comment]
Try to add this 


echo "MY Progress app "
response=$(osascript -e 'tell app "System Events" to display dialog "
Program is ready click OK to run
Cancel for EXIT😃"System:Library:CoreServices:Installer.app:Contents:Resources:Installer.icns" buttons {"Cancel", "OK"} default button 2 with title "BUILD"')
answer=$(echo $response | grep "OK")

# Cancel is user does not select OK
if [ ! "$answer" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  exit 0
fi

**Comment by cylott** [comment]
Thanks, you're right there are several alternative ways of doing this.
