### ISSUE TITLE
How to write to a file in working directory from a bash script

### ISSUE THREAD

**Issue by jkurei** [sveinbjornt/Platypus#141]
Hi! I'm trying to use Platypus to wrap a bash script that needs to read a file from the working directory and write to a new file right there, but I don't want to hardcode this path.

However, if I try to read from "./filename.txt", or write to it, I'm accessing files inside of the app bundle, like `/Users/me/Desktop/Test.app/Contents/Resources`. I've tried variables like `$PWD` and `$0` and they all point to the insides of this bundle. 

Can I use platypus to create apps that access their working directory? 

My best chance seems to be to read `$PWD` and sed the `Test.app/Contents/Resources` out, but I was hoping there was a more elegant way.

Thanks a lot, and thanks for Platypus!

**Comment by sveinbjornt** [comment]
`cd ../../..` should do the trick.
