### ISSUE TITLE
Improve interpreter bundling since Apple is removing interpreters in Catalina

### ISSUE THREAD

**Issue by sveinbjornt** [sveinbjornt/Platypus#142]
https://www.macobserver.com/analysis/macos-catalina-deprecates-unix-scripting-languages/

    Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for 
    compatibility with legacy software. Future versions of macOS won’t include scripting 
    language runtimes by default, and might require you to install additional packages. If your 
    software depends on scripting languages, it’s recommended that you bundle the runtime 
    within the app. (49764202)

**Comment by sveinbjornt** [comment]
Well, all the interpreters are still in their place in Big Sur, so I'm not sure how much I need to worry about this for now.

**Comment by Kerrick** [comment]
Python 2.7 was removed from macOS 12.3, so it seems Apple has started making good on this promise. https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python

**Comment by sveinbjornt** [comment]
Yeah, and I think Python 3 is only installed with the Xcode Developer Tools.
