### ISSUE TITLE
(1) shc: Platypus w/ C-compiled shell script? / (2) Default code location for script instead of Resources

### ISSUE THREAD

**Issue by JayBrown** [sveinbjornt/Platypus#143]
(1) There's a neat little tool called **[shc](http://neurobin.github.io/shc/)** that let's you C-compile shell scripts. People are using it to obfuscate their scripts, but my approach is that a C-compiled script is an executable, and it can be code-signed for Platypus app distribution.

I have tried building a Platypus app with such a compiled script, but it didn't work. Anyone with more luck? If yes, how did you do it?

(2) Regarding code-signing there is then a logical follow-up question: Platypus puts the script in ./Contents/Resources, but that directory, like ./Contents/Extras etc., is not a default code location. Default code locations for app bundles are:

* ./Contents/MacOS
* ./Contents/Frameworks
* ./Contents/PlugIns
* ./Contents/XPCServices
* ./Contents/Helpers
* ./Contents/Library/Automator
* ./Contents/Library/Spotlight
* ./Contents/Library/LoginItems

Would it be possible to have an additional setting in Platypus that lets the user determine the location of the script, e.g. ./Contents/MacOS? That would be awesome.

**Comment by sveinbjornt** [comment]
1) Why not just invoke your compiled binary via a shell script? Platypus assumes that you are running a script that is provided as an argument to an interpreter

2) Why does it matter where the script is located?
