### ISSUE TITLE
Running App as root with applescript prompt not working

### ISSUE THREAD

**Issue by Shocco** [sveinbjornt/Platypus#144]
I am calling applescript from bash (osapplescript) to ask the user for input. please see below
"
Username=$(osascript -e 'to getusername()
display dialog "something" default answer ""
set userid to text returned of result
end getusername
set userid to getusername()')
"
echo $Username
and it works by itself and with the echo
but when i do more detailed things it doesnt even prompt anymore.

i am also doing this as admin (via the checkbox) 

is this a by design issue or is it something else?

**Comment by sveinbjornt** [comment]
This may be an issue with AppleScript. When the script is run with admin privileges, the effective UID becomes 0 (root) whereas the Window Server is probably tied to your current user account.

**Comment by Shocco** [comment]
but im using applescript to get that value and its not prompting me at all unless its something simple like described

the short of what im doing is trying to make it "easier" to enable filevault2 FDE

im using the above as the password and then doing

Pass=$(osascript -e 'to getusername()
display dialog "something" default answer ""
set userid to text returned of result
end getusername
set userid to getusername()')

fdesetup enable --user $USER -p  \'$Pass\'

**Comment by JayBrown** [comment]
Maybe you can try the following, a workaround to have GUI support in AppleScript with privilege escalation:

```
loggedinusername=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/{print $3}')
loggedinuserid=$(id -u "$loggedinusername")
launchctl asuser "$loggedinuserid" osascript -e foo
```

Note: obviously you need to replace `foo` with your AppleScript.

**Comment by sveinbjornt** [comment]
It turns out that /bin/bash cannot run with root privileges via Apple's Security framework. /bin/sh works fine, however.
