### ISSUE TITLE
Created CMD app wit Platypus but no dock icon

### ISSUE THREAD

**Issue by mgscreativa** [sveinbjornt/Platypus#148]
Hi! Created gedit launcher app with Platypus 5.3, selected png icon from folder, and created the app in the Applications folder, so far so good, but after app creation, and running the launcher, the dock icon remains blank.

How can I change that?

Thanks!
![Captura de Pantalla 2019-08-24 a la(s) 13 21 58](https://user-images.githubusercontent.com/1286632/63640058-494f0e80-c672-11e9-9fcf-296ab08ae706.png)

**Comment by sveinbjornt** [comment]
Does this persist after restarting the Finder/OS? Is the PNG image peculiar in some way or broken? Is the icon only like this in the Dock?
