### ISSUE TITLE
identified as "win.trojan.pistacchietto"?

### ISSUE THREAD

**Issue by jdelaphant** [sveinbjornt/Platypus#149]
Since about a week ago, everything associated with the current version of Platypus is being flagged by my antivirus software as "win.trojan.pistacchietto" and blocked from running. This includes php apps that I build with platypus, as well as new copies of platypus that I download. 

Is this an actual infection, or a false positive?

The antivirus software that I'm using is CISCO Amp for Endpoints, it's based on ClamAV(osx.cvd 295)

**Comment by sveinbjornt** [comment]
False positive. All unsigned Platypus-generated apps obviously have the same binary (and hence same fingerprint). In the past, some people have created malicious apps with Platypus, this may cause some simplistic virus software to falsely identify every Platypus binary as malicious.
