### ISSUE TITLE
When running "which" command, in shell script, value is always considered blank.

### ISSUE THREAD

**Issue by TransmissionsDev** [sveinbjornt/Platypus#152]
My script looks like this:

```bash
echo "-- Checking for existing kenkashworld on PATH..."
HAS_KEN_TOOLS=$(which kenkashworld)

if [ ! -z "$HAS_KEN_TOOLS" ]
then
    echo "Your machine already has kenkashworld installed. Nothing to do."
    echo "-- All done!"
    exit 0
fi
```

When I run the script by running the app generated by Platypus, the `echo "Your machine already has kenkashworld installed. Nothing to do."` never occurs, nor the exit or the other echo. 

When I print the value of `which kenkashworld` later in the code:

```bash
echo "-- kenkashworld is now installed at $(which kenkashworld)"
```

It also prints that `which kenkashworld` is blank..

This shouldn't happen because when I run `which kenkashworld` it prints `/usr/local/bin/kenkashworld`.

The weirdest part is that when I go into the package contents and manually double click on the script in resources, it works just fine.

Can you help me?

**Comment by sveinbjornt** [comment]
Platypus doesn't automatically run the scripts via a login shell and so doesn't get the user's PATH settings.

Assuming that you're using bash, you can set the interpreter to `/bin/bash` and add the `-l` flag as an argument under "Args". This makes bash act as if it had been invoked as a login shell. See `man bash` for details.

Another alternative is to manually load the user's shell configuration file in your script:

````
source ~/.bashrc
````

For other shells, consult their respective documentation.
