### ISSUE TITLE
Allow symlinks as bundled files.

### ISSUE THREAD

**Issue by saulspatz** [sveinbjornt/Platypus#157]
I have an app on my Mac that may update two files.  If I add them as bundled files, they are copied into the resource folder, and updates don't affect the original files.  What I do now is add the files, then go into the Resources folder on the command line, delete the files, and replace them with symlinks to the actual files.  I have to do this any time I maintain the app.  It would be a lot more convenient if Platypus had a facility to bundle soft links.

**Comment by sveinbjornt** [comment]
When you press "Create App", the ensuing file save dialog should contain the option "Create symlink to script and bundled files". Does this not work for you?

**Comment by saulspatz** [comment]
I completely overlooked that; thanks.
