### ISSUE TITLE
Allow script to set console color

### ISSUE THREAD

**Issue by olivervbk** [sveinbjornt/Platypus#158]
**Snippet (Shell/bash/etc interpreter):**
```
printf "\033[0;31m"
echo red text
printf "\033[0m"
```

**Expected:**
red text _(in red color)_

**Actual:**
```
[0;31mred?
[0m
```

Also tested with: zsh,perl,python.
tput in sh also doesn't work.

**Comment by sveinbjornt** [comment]
As stated in the documentation, Platypus apps are NOT terminal emulators and never will be. If you want full terminal functionality, run the script in the terminal!
