### ISSUE TITLE
Invalid Bundle Identifier

### ISSUE THREAD

**Issue by peetinc** [sveinbjornt/Platypus#160]
Apologies in advance if I'm missing something, but I've tried using my .consulting domain to create apps with Platypus, but I get an Invalid Bundle Identifier error and can go no further i.e. "consulting.artichoke.SuperAwesomeApp".

Apple describes the CFBundleIdentifier (Bundle identifier) as 

> The bundle identifier string identifies your application to the system. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. The string should also be in reverse-DNS format. For example, if your company’s domain is Ajax.com and you create an application named Hello, you could assign the string com.Ajax.Hello as your application’s bundle identifier.
The bundle identifier is used in validating the application signature.

It seems as though the validity check is partially based on length, 6 characters is okay, but 7+ is not. "consul.artichoke.SuperAwesomeApp" is Platypus approved, but "consult.artichoke.SuperAwesomeApp" and of course "consulting.artichoke.SuperAwesomeApp" are not.

I think that technically the longest TLD in the [ICANN list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) is 24 characters (XN--VERMGENSBERATUNG-PWB) One's got to wonder what the heck that was/is for ...

Thanks.Peet

**Comment by sveinbjornt** [comment]
Now fixed in master.

**Comment by peetinc** [comment]
Thanks so very much! It took me bit to figure out how to build the project without a signature, but done and it seems to work correctly.
