### ISSUE TITLE
FR: Allow hiding of Cancel/Quit button in Progress Bar

### ISSUE THREAD

**Issue by iJake** [sveinbjornt/Platypus#161]
Want the app to be completely controlled by a script that will open and close the Progress Bar app. Closing the Progress Bar will have no bearing on the running of the underlying process so would be great if we could hide those buttons

**Comment by sveinbjornt** [comment]
Sorry but this is such a specialised need that I don't think is worth implementing. If you really don't want the Cancel/Quit button, you can edit the nib file in the resulting application and simply remove the button manually.
