### ISSUE TITLE
Issue ctrl-c to running script when exiting

### ISSUE THREAD

**Issue by henrik242** [sveinbjornt/Platypus#164]
I run a script that maintain my VPN connectivity in a script window.  Could it be possible to send a ctrl-c to the running script when pressing cancel on the script window?  Or maybe introduce an Exit button which does that?

Thanks.

**Comment by sveinbjornt** [comment]
At the moment, Platypus apps send a SIGTERM to the script when Cancel is pressed. Can't you intercept that?

**Comment by henrik242** [comment]
Hmmm, probably. The script is no longer in use, so I don't know if I'll ever try again :) Closing this for now.
