### ISSUE TITLE
Does Apple accept Platypus apps in the macOS app store?

### ISSUE THREAD

**Issue by ad-si** [sveinbjornt/Platypus#168]
Is it possible to distribute apps created with Platypus via the macOS app store?
Are there any known apps which are sold via the app store?

**Comment by cylott** [comment]
> Is it possible to distribute apps created with Platypus via the macOS app store?
> Are there any known apps which are sold via the app store?

Does Apple allow any apps on the App store that aren't made with Xcode? I can think of one, which iirc is a collection of scripts wrapped in a (java??) UI:
https://apps.apple.com/us/app/filebot/id905384638?mt=12

I doubt a Platypus app is allowed but if you make any progress please let us know!

**Comment by sveinbjornt** [comment]
I'd imagine that if you sign it and zip it in the right, the whole thing should work just fine.

See: https://github.com/sveinbjornt/Platypus/issues/169
