### ISSUE TITLE
Typing in the password window is not working

### ISSUE THREAD

**Issue by NewsGuyTor** [sveinbjornt/Platypus#170]
I'm having a weird issue with my [BootToWin](https://github.com/NewsGuyTor/BootToWin) project.

The password box is unresponsive the first time, but the second/third time it is displayed typing starts working.

Full source code and Platypus project is in the repo linked above, but here's the relevant script:

> set bootToWindowsAlert to "Restart to Windows?"
> set bootToWindowsConfirm to "You are about to restart into Windows. Are you sure?"
> display alert bootToWindowsAlert message bootToWindowsConfirm as critical buttons {"Cancel", "Restart"} default button "Restart" cancel button "Cancel"
> do shell script "WINDIRVAR=$(systemsetup -liststartupdisks | grep WINDOWS | sed 's/\\/WINDOWS//g') && bless -mount $WINDIRVAR --setBoot && osascript -e 'tell application \"System Events\" to restart'" password "" with administrator privileges

**Comment by sveinbjornt** [comment]
I take it you using Platypus to bundle an AppleScript? Why not just use Automator?
