### ISSUE TITLE
Platypus using Graphviz

### ISSUE THREAD

**Issue by lcoandrade** [sveinbjornt/Platypus#172]
I've made a python script using Graphviz. When I try to run the app generated with Platypus, I get this:

`graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'diagrama_relacoes'], make sure the Graphviz executables are on your systems' PATH`

The problem is that I have dot on my PATH. Running which dot returns `/usr/local/bin/dot`.

How can I solve this?

PS. Great App!

**Comment by sveinbjornt** [comment]
I suggest providing the full path to binary you're calling. Scripts running through a Platypus app do not inherit the user's PATH (and in fact do not spawn a shell unless explicitly programmed to do so).
