### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by cylott** [sveinbjornt/Platypus#174]
Just watched the WWDC keynote. I've heard @sveinbjornt say in the past that the codebase for Platypus is old.. here's to hoping this critical mac resource will make the jump to ARM!

**Comment by sveinbjornt** [comment]
The codebase is indeed quite old, with the oldest being from 2003, but I've regularly refactored and modernised over the years. There's nothing processor-architecture-specific. I see no reason why Platypus for ARM shouldn't just be a simple recompile.

**Comment by cylott** [comment]
> The codebase is indeed quite old, with the oldest being from 2003, but I've regularly refactored and modernised over the years. There's nothing processor-architecture-specific. I see no reason why Platypus for ARM shouldn't just be a simple recompile.

Amazing, that is incredible news! Now let's hope all the linux tools and macports packages we use to actually make these apps compile on ARM...

**Comment by JayBrown** [comment]
Would it be possible for Platypus to build universal binary Platypus apps, even if the originating macOS is running on an Intel Mac? (I assume that Platypus itself might need to be a universal binary too.)

As for tools, MacPorts, Homebrew et al., I hope that they will offer options to install universal binary versions. At least with Homebrew that shouldn't be a problem, with their precompiled bottle approach.

I do have a couple of tools I use nested in Platypus apps, and it would be insane if I had to buy a new ARM Mac, just to compile tools, Platypus apps etc. that will work on all platforms. Definitely interesting times ahead.

**Comment by cylott** [comment]
With the two punch of no more bundled interpreters and ARM, this will be "interesting" indeed...

**Comment by sveinbjornt** [comment]
Platypus made the transition from PowerPC to Intel back in 2005 without much trouble, and I'm not at all worried about this one. Both Platypus.app and the included ScriptExec binary will simply be recompiled as "fat" x86_64/ARM binaries that run natively on both architectures.

@cylott The removing of various interpreters from macOS is a much bigger cause for concern, since it means that Platypus apps will need to bundle them with the app... :/

**Comment by cylott** [comment]
> @cylott The removing of various interpreters from macOS is a much bigger cause for concern, since it means that Platypus apps will need to bundle them with the app... :/

Exactly.. I'm especially concerned about this as my apps are written in PHP. I've never had luck doing a static build of PHP, ever. The result is that everyone is going to need to install MacPorts or Homebrew first and tell the app where the binary is. Sigh...
