### ISSUE TITLE
corrupt app bundle script missing from application bundle

### ISSUE THREAD

**Issue by ghost** [sveinbjornt/Platypus#175]
![280E0576-2503-405C-B151-9C51108969BB_4_5005_c](https://user-images.githubusercontent.com/32454896/88146152-c3c63c80-cbfb-11ea-85f0-e0a42abfc0e7.jpeg)

**Comment by sveinbjornt** [comment]
You'll have to provide a bit more information than this. This error is shown if Platypus was unable to copy your script to the application bundle. Does your user account have read access to the script file in question?
