### ISSUE TITLE
Status Menu - Dynamic menu bar icon change

### ISSUE THREAD

**Issue by bobharrisbtt** [sveinbjornt/Platypus#176]
When using a Platypus "Status Menu" app, can we have a way to dynamically change either the Menu bar icon or the "Text" on the menu bar via a write to stdout.

In my case I have a script that connects and disconnects from a VPN, and it would be nice if the Menu bar icon could change to indicate if the VPN was connected or disconnected.

Something like
printf "MENU_BAR_ICON|my_vpn_connected.png\n"
or
printf "MENU_BAR_ICON|my_vpn_disconnected.png\n"

Or for text
printf "MENU_BAR_TEXT|VPN On\n"
or
printf "MENU_BAR_TEXT|VPN Off\n"

The actual command syntax is totally up to you.  I just tried to pattern it off of existing directives a "Status Menu" Platypus app accepts.

Thank you.

**Comment by sveinbjornt** [comment]
This is a good idea, I'll put it on the upcoming feature list.

**Comment by JayBrown** [comment]
There's a great little app called **[AnyBar](https://github.com/tonsky/AnyBar)** that does something similar (only colors)… and of course **[BitBar](https://github.com/matryer/bitbar)** also has dynamic menu bar icons that the user can set, incl. Base64-encoded images.

**Comment by sveinbjornt** [comment]
This has now been implemented in master and will be part of Platypus 5.4. The syntax is the following:

To control status item title, print to stdout:
STATUSTITLE|My title

and to set icon:
STATUSICON|[bundled image name|absolute path to file|remote url]

e.g. 

STATUSICON|myfile.png
or
STATUSICON|/path/to/my/favourite/file.png
or
STATUSICON|https://myserver.com/images/image.png

Thank you for your feedback.
