### ISSUE TITLE
[FR] Add option not to get the focus when a file is opened by the app

### ISSUE THREAD

**Issue by NightMachinary** [sveinbjornt/Platypus#178]
I use Platypus to open some files such as `wav`, `zip`, etc. The app doesn't need to get the focus from Finder, as its GUI is only a debugging aid and unnecessary. Can there an option not to get the focus, or at least to give it back immediately?

**Comment by sveinbjornt** [comment]
If I remember correctly, the "Run in background" mode does this.

**Comment by sveinbjornt** [comment]
If not, this is such a specialised use case that it makes absolutely no sense to add it as a togglable behaviour.
