### ISSUE TITLE
"Help" menu + Platypus support for .help bundles (macOS HelpViewer)

### ISSUE THREAD

**Issue by JayBrown** [sveinbjornt/Platypus#179]
I've noticed that Platypus apps don't have a "Help" Menu (which would normally contain a "<myAppName> Help command").

It would be great if that could be implemented. Of course the app developer would then still have to manually create a `.help` bundle (before or after) to include in `./Contents/Resources`.

Possible?

**Comment by sveinbjornt** [comment]
Definitely possible, and a good idea. On the upcoming features list.

**Comment by JayBrown** [comment]
Awesome. For those interested, here's a current article on how to actually create `.help` bundles for modern macOS applications: https://marioaguzman.wordpress.com/2020/09/12/auth/
