### ISSUE TITLE
Platypus works from GUI but same command fails in CLI

### ISSUE THREAD

**Issue by strawberrydit** [sveinbjornt/Platypus#182]
Very strange issue. Building a command with the GUI executes correctly and creates a proper application that functions. Going to "Action > Show Shell Command" and pasting that into the terminal produces a failed application. The issue appears to be related to optimizing the nib file.

MacOS v10.15.7
Xcode v12.1
Homebrew 2.5.9
Platypus CLI version 5.3
Platypus GUI v5.2 or v5.3

Installed platypus via brew:
```
$ brew install cask platypus
```

```
$ which platypus
/usr/local/bin/platypus
$ platypus --version
platypus version 5.3
```

This is the command I set up in the GUI, which builds a functional file IN THE GUI but NOT when run from the terminal. Upon saving it, you can check or uncheck "Strip nib file to reduce app size" and it will produce a proper application.
```
/usr/local/bin/platypus --background --quit-after-execution --app-icon '/private/var/folders/99/4d8ks8s17bsgtbxv3_q0z5gw0000gn/T/AppTranslocation/3E722604-680E-4A81-A03B-3829E13E2B04/d/Platypus.app/Contents/Resources/PlatypusDefault.icns'  --name 'VH16XAswapMONAB'  --interface-type 'None'  --interpreter '/bin/bash'   --bundle-identifier com.sbc.VH16XAswapMONAB  '~/Desktop/VH16XAswapMONAB.sh'
```

If you run that in the CLI, this happens:

```
Creating application bundle folder hierarchy
Copying executable to bundle
Copying nib file to bundle
Optimizing nib file
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.ibtool.errors</key>
	<array>
		<dict>
			<key>description</key>
			<string>Interface Builder could not strip "MainMenu.nib". The format is not recognized.</string>
		</dict>
	</array>
</dict>
</plist>
Copying script to bundle
Writing AppSettings.plist
Writing application icon
Writing Info.plist
Moving app to destination ~/Desktop/VH16XAswapMONAB.app
Registering app with Launch Services
Done
```

Resulting application will not open and has an alias to
```
VH16XAswapMONAB
```
in place of the binary. 

This is the .sh file: (Needs to be renamed, GITHUB doesn't accept .sh)
[VH16XAswapMONAB-RENAME_AS_SH.txt](https://github.com/sveinbjornt/Platypus/files/5519864/VH16XAswapMONAB-RENAME_AS_SH.txt)

Interestingly enough, this works on another machine whose only difference is that platypus is installed here:
```
/usr/local/Cellar/platypus/5.3/bin/platypus
```

I don't know why its in this location, I would have installed from brew the same as depicted above. It also reports v5.3.

Am I doing something obviously wrong here or is this a bug?

Thank you for your time.

**Comment by sveinbjornt** [comment]
Fixed in master, command line tool no longer defaults to stripping nib file.
