### ISSUE TITLE
Enable closing ⓧ button for text window

### ISSUE THREAD

**Issue by ad-si** [sveinbjornt/Platypus#183]
Is there a way to enable the red window closing button for text windows and web views? It's quite unintuitive that you have to click a separate "Quit" button.

**Comment by chris1111** [comment]
# Vars
apptitle="YOUR APP NAME"
version="1.0"
# Set Icon directory and file 
iconfile="/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns"

response=$(osascript -e 'tell app "System Events" to display dialog "The first step is to select your USB key\n\nSelect USB to continue Cancel for Quit" buttons {"Cancel","USB"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)


# Exit if Canceled
if [ "$action" == "Cancel" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  exit 0
fi

**Comment by ad-si** [comment]
Uhm, what exactly am I looking at? 😅

**Comment by chris1111** [comment]
> Uhm, what exactly am I looking at? 😅

a button continue or exit for Text window exactly what you said

**Comment by ad-si** [comment]
I think you misunderstood. What I want is to use the **native** windows closing window. However, as you can see in following screenshot, it is disabled per default:

![image](https://user-images.githubusercontent.com/36796532/102616672-d05dab00-412f-11eb-956f-5a9ea407d819.png)

Now the question is: How can I reenable it / activate it?

**Comment by chris1111** [comment]
> I think you misunderstood. What I want is to use the **native** window closing button. However, as you can see in following screenshot, it is disabled per default:
> 
> ![image](https://user-images.githubusercontent.com/36796532/102616672-d05dab00-412f-11eb-956f-5a9ea407d819.png)
> 
> Now the question is: How can I reenable it / activate it?

Ha ok Sorry 😂 You need to edit the **MainMenu.nib** file with Xcode

![Capture d’écran, le 2020-12-18 à 08 45 27](https://user-images.githubusercontent.com/6248794/102621514-aeebc780-410d-11eb-8344-1d2837fdfd51.png)

To do this when you creat the app you need Unchek the box
![Capture d’écran, le 2020-12-18 à 08 51 41](https://user-images.githubusercontent.com/6248794/102622025-7698b900-410e-11eb-8835-b4a0fb762d84.png)

**Comment by sveinbjornt** [comment]
Changed in master. New behaviour across the board: All windows  now have an enabled close button which quits the app when pressed.

Back in the days, such behaviour was a violation of the Apple Human Interface Guidelines. Apps were to stay open even if their only window was closed. But not even Apple seems to abide by these rules any more, and only old Mac guys like me seem to like them. :/

**Comment by ad-si** [comment]
I just tried this out with the latest HEAD, but the x is still grayed out.
Here is how I use Platypus: https://github.com/ad-si/Perspec/blob/master/makefile

Do I have to enable it somehow?

**Comment by sveinbjornt** [comment]
Strange. Have you tried uninstalling and reinstalling the command line tool? Does this also happen when you create an app using the GUI app?

**Comment by ad-si** [comment]
@sveinbjornt When I create an app with the GUI, the x button works.
I've also built all the example apps with `make_examples.pl`, but "SpeakDroplet" was the only one of them with a working x button.
