### ISSUE TITLE
Is it possible to format text in a status menu?

### ISSUE THREAD

**Issue by avnerbarr** [sveinbjornt/Platypus#184]
I'd like to customize the fonts and colors of the menu items. Is this possible?

**Comment by sveinbjornt** [comment]
This is currently not possible but may make it as a feature into a future version.

**Comment by sveinbjornt** [comment]
Should be possible but apparently not working on latest macOS. This is a bug.

**Comment by sveinbjornt** [comment]
No, this is only an issue when previewing status item in the Platypus app. Works fine when you generate the app and run it.
