### ISSUE TITLE
trying to disable a submenu item doesn't seem to work

### ISSUE THREAD

**Issue by avnerbarr** [sveinbjornt/Platypus#185]
I'd like to disable the submenu item but seems that I can only disable the full item

`SUBMENU|Root|Val1|DISABLED|Val2`

**Comment by sveinbjornt** [comment]
Disabling submenus is currently not supported but may make it into future versions as a feature.

**Comment by sveinbjornt** [comment]
Implemented in master, will make it into 5.4 release.
