### ISSUE TITLE
Platypus beeps on launch if the command line tool is not installed

### ISSUE THREAD

**Issue by ShakeThat** [sveinbjornt/Platypus#187]
This happens when the app tries to load /usr/local/share/platypus/PlatypusDefault.icns, which exists only if the optional command line tool has been installed. The reason for the beep is not evident to the user, and it may be a cause for concern. I did not investigate why the icon is being loaded from that location rather than from the app bundle.

Assuming there is a good reason for trying to load it from that location, then I suggest (1) if the user chose not to install the command line tool, suppress the beep; and (2) if the user _did_ choose to install the command line tool yet the icon is missing, a beep should be accompanied by an alert or at minimum a log message.

**Comment by sveinbjornt** [comment]
Fixed in master.
