### ISSUE TITLE
Status Menu Interface: distinguish left and right click

### ISSUE THREAD

**Issue by huwan** [sveinbjornt/Platypus#188]
I have been trying to develop a simple menu bar application which triggers the screen saver using applescript if you press status menu bar icon.
 
```
tell application "System Events"
    start current screen saver
end tell
```

The problem here is I cannot quit the app from its menubar, though a default"Quit AppName" menu item exists. Because the script is immediately run when the status item is pressed. One possible solution is using right click. If you right click it displays a menu with the Quit item. However, it seems Platypus doesn't distinguish left/right mouse click at the moment.

Is there any plans to support this or is there a workaround? Thanks in advance and any help appreciated!

**Comment by chris1111** [comment]
> I have been trying to develop a simple menu bar application which triggers the screen saver using applescript if you press status menu bar icon.
> 
> ```
> tell application "System Events"
>     start current screen saver
> end tell
> ```
> 
> The problem here is I cannot quit the app from its menubar, though a default"Quit AppName" menu item exists. Because the script is immediately run when the status item is pressed. One possible solution is using right click. If you right click it displays a menu with the Quit item. However, it seems Platypus doesn't distinguish left/right mouse click at the moment.
> 
> Is there any plans to support this or is there a workaround? Thanks in advance and any help appreciated!

Try this ⬇︎

> apptitle="Screen Saver"
> version="1.0"
> # Set Icon directory and file
> iconfile="/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns"
> Sleep 1
> response=$(osascript -e 'tell app "System Events" to display dialog "
> Screen Saver\nCancel for exit" buttons {"Cancel" ,"Screen Saver" default button 2 with title "'"$apptitle"' '"$version"'"  with icon POSIX file "'"$iconfile"'"  ')

> tell application "System Events"
>     start current screen saver
> end tell
> ```
>

**Comment by chris1111** [comment]
More easy to me post a script
See my script then let me know if that help you

[script.zip](https://github.com/sveinbjornt/Platypus/files/6526706/script.zip)

**Comment by huwan** [comment]
Thank you for sharing the script and providing a second perspective. 

But I hope there is a way to trigger the screen saver with just **ONE** click on the status menu. This can be done with current platypus. But I don't find a solution to quit the app excluding "Force Quit".

I find a similar app which can trigger screen saver by just right-clicking menu bar icon: https://github.com/jamieweavis/afk

Thanks.
