### ISSUE TITLE
extend docs

### ISSUE THREAD

**Issue by iwan-uschka** [sveinbjornt/Platypus#190]
Please add to the docs that status menu bar functionality like
- icons
- submenus
- handling arguments
is not available in the preview (via "status item settings").

I tried the preview for ages until i finally tried the app itself :)

Thx. Great project!!

**Comment by sveinbjornt** [comment]
Fixed in master, this fact is now noted in the Status Item Settings dialog.

https://github.com/sveinbjornt/Platypus/commit/c62fea75565e28023f08d6ddc16a758f1e7d322c
