### ISSUE TITLE
When will 5.4 be released?

### ISSUE THREAD

**Issue by mlcampbe** [sveinbjornt/Platypus#191]
There are a couple of issues/features available in version 5.4 I would like to take advantage of. Can you give a rough estimate when that might be released?

**Comment by sveinbjornt** [comment]
Not really. I am very busy with my real job, but hopefully sometime later this year. Meanwhile, you can always build the latest version from the master branch.

**Comment by mlcampbe** [comment]
I downloaded the master branch and successfully compiled it to get the feature I was looking for. However, 5.4 seems to break the DISABLED status menu option for some reason. If I use this:

print "DISABLED:this is a menu item"

Then it does not show up at all. It is not there, not greyed out, nothing. Is there a change in 5.4 to the way to disable menu items?

**Comment by sveinbjornt** [comment]
The syntax, as noted in the documentation, is "DISABLED|Title of menu item", i.e. the |-symbol separator is used.

However, in the course of checking this out, I discovered another bug which caused disabled items not to appear. So thank you!

**Comment by mlcampbe** [comment]
Ok thanks then I am not crazy. I used DISABLED|xxx successfully in the 5.3 version but it mysterious broke in 5.4. We you be fixing the bug or can you tell me where the bug is at and I can fix it myself.

**Comment by sveinbjornt** [comment]
Already fixed in master.

**Comment by sveinbjornt** [comment]
Out of curiosity, what was the new feature in 5.4 that you needed?

**Comment by mlcampbe** [comment]
Thanks for the quick turnaround. You can go ahead and close this issue out as I assume that the fix will take care of it.

I wanted to use the ability to change the status icon based on the output from my script.
