### ISSUE TITLE
Cannot get statusicon to work in 5.4

### ISSUE THREAD

**Issue by mlcampbe** [sveinbjornt/Platypus#192]
I downloaded and compiled version 5.4 to get the STATUSICON option. However, I cannot get that to work as I thought it would. For example I have the following code:

    if [ "$#" -eq 0 ]; then
      check_state
      if [[ "${STATE}" == "Connected" ]]; then
        echo "STATUSICON|lock.png"
        echo "DISABLED|Enable App"
        echo "Disable App"
      else
        echo "STATUSICON|unlock.png"
        echo "Enable App"
        echo "DISABLED|Disable App"
      fi
      echo "----"
      echo "icon error.png"
    fi

    if [[ $1 == icon* ]]; then
      echo "icon" >> /tmp/abc
      echo "STATUSICON|error.png"
    fi

    if [[ $1 == Disable* ]]; then
        /path/to/app disconnect
        echo "STATUSICON|unlock.png"
    fi

So it builds the menu correctly and when I select the "icon error.png" option from the menu I can see that the word icon is printed into the /tmp/abc file as expected meaning that the if statement matched the parameter. However, I never see the status icon change from here. The call to check_state at the top successfully changes the icon but after it is set that 1 time I never seem to be able to change it again. 

Any ideas?

**Comment by sveinbjornt** [comment]
As it is, the undocumented STATUSICON and STATUSTITLE syntax (recently added by a 3rd party contributor) is only supported when building the contents of the menu. The output of the command when a menu item is selected is ignored.

**Comment by mlcampbe** [comment]
Thank would explain it. Thanks!
