### ISSUE TITLE
How to pack with Python interpreter and the packages in Anaconda virtual envs 

### ISSUE THREAD

**Issue by GraceKafuu** [sveinbjornt/Platypus#193]
Hi, thanks for your great works, I have read #146 , but still can't get through, can you tell us more detailed.

**Comment by sveinbjornt** [comment]
Include your virtualenv in Bundled Files. Use a shell script.  Have the shell script activate the virtualenv and run your Python program.

**Comment by GraceKafuu** [comment]
> Include your virtualenv in Bundled Files. Use a shell script. Have the shell script activate the virtualenv and run your Python program.

Could you please give me an example with pictures, I am not very clearly. Thank you in advance.

**Comment by kMikaZu** [comment]
I would like to have an example as well.
