### ISSUE TITLE
Documentation link to CocoaDialog seems to be broken

### ISSUE THREAD

**Issue by dtgriscom** [sveinbjornt/Platypus#194]
If you choose "Platypus Documentation" from the "Help" menu, then it opens the file at `file:///Applications/Platypus.app/Contents/Resources/Documentation.html` in your web browser (good). But, in the "What Platypus is NOT" section, there's a link to CocoaDialog, which leads to `file:///Applications/Platypus.app/Contents/Resources/User%20interaction%20with%20CocoaDialog`, which doesn't exist.

It looks like this is supposed to be a reference to the "User interaction with CocoaDialog" section later in the document.

**Comment by sveinbjornt** [comment]
Thanks, fixed in master.

https://github.com/sveinbjornt/Platypus/commit/7a81bcdf92b0d7bbae28564a6961e6cfcb398324
