### ISSUE TITLE
Confirmation Step

### ISSUE THREAD

**Issue by manngo** [sveinbjornt/Platypus#196]
Is it possible to include a confirmation dialog with the application? Something like:

![image](https://user-images.githubusercontent.com/3796633/132812359-255b988e-9fad-4931-ad86-37fe7e44185d.png)

This would give the user the chance not to go ahead with the running application.

Thanks for a brilliant product!

**Comment by sveinbjornt** [comment]
As noted in the documentation, you may be able to add interactive GUI elements to a Platypus app via CocoaDialog or AppleScript.

https://github.com/sveinbjornt/Platypus/blob/master/Documentation/Documentation.md#prompting-for-input-via-osascriptapplescript

**Comment by manngo** [comment]
Ah, thanks for that. I managed by adding the following at the beginning of shell script:

```sh
CONFIRM=$(osascript -l JavaScript <<EOT
	var app = Application.currentApplication();
	app.includeStandardAdditions = true;

	app.displayDialog('Are you sure?', {
		withTitle: 'Confirm',
		buttons: ["No", "Yes"],
		defaultButton: "Yes",
		cancelButton: "No"
	});
EOT)

if [ "$CONFIRM" = "buttonReturned:Yes" ]; then
	#	Do something
else
	echo "Bye Bye"
fi
```

(JavaScrpt because I feel more comfortable with it).
