### ISSUE TITLE
Getting the Working Directory of the Application

### ISSUE THREAD

**Issue by manngo** [sveinbjornt/Platypus#197]
I know that the shell script finds its way into the `….app/Contents/Resources/` directory. Is there a simple way of getting the app directory? Currently I use this:

```sh
	dir=$(builtin cd "../../.."; pwd)
```

It works, but I wondered whether there is a more direct approach?

**Comment by sveinbjornt** [comment]
As noted in the documentation:

https://github.com/sveinbjornt/Platypus/blob/master/Documentation/Documentation.md#how-do-i-get-the-path-to-my-application-andor-bundled-files-from-within-the-script

What do you mean by "more direct approach"?

**Comment by manngo** [comment]
No, that’s pretty clear. I wondered whether there might be an argument or something like that.
Thanks again.
