### ISSUE TITLE
Terminal download instruction is outdated

### ISSUE THREAD

**Issue by aditya2604** [sveinbjornt/Platypus#199]
The homebrew download instruction on the [website](https://sveinbjorn.org/platypus) is outdated. It shows `brew cask install platypus` when it should be `brew install --cask platypus`.

![Screen Shot 2021-09-18 at 11 35 01 PM](https://user-images.githubusercontent.com/59426357/133917987-d334afa6-cded-4c5f-b9c4-62ed15905b98.png)

**Comment by sveinbjornt** [comment]
Fixed.
