### ISSUE TITLE
App created with v5.3 prompts python warning on macOS 12

### ISSUE THREAD

**Issue by Coros** [sveinbjornt/Platypus#200]
I have an app with a zsh embedded script that alerts a python2 warning when run on macOS 12.  The script I'm using does not utilize python in anyway.  Does platypus run a check for python upon execution that would trigger this warning?

**Comment by sveinbjornt** [comment]
No, it only checks if the selected interpreter exists on the system. Platypus and Platypus apps do not use or rely on Python in any way unless you choose a Python interpreter. I do not have access to macOS 12, so I am unable to replicate this issue.

**Comment by Coros** [comment]
I may have figure it out.  One of the resources I included in the app does appear to use python.  I'll report back once I've confirmed and resolved the issue.

**Comment by chris1111** [comment]
I have the same issue on  such a script
See [release note about Python](https://developer.apple.com/documentation/macos-release-notes/macos-12_0_1-release-notes)
Python
Deprecations
If an app uses Python 2.7, macOS now triggers an alert indicating that the developer must update the app to ensure it will work in future versions of macOS. (80221011)

**Comment by sveinbjornt** [comment]
This is expected behaviour, since Apple is deprecating Python 2.7 support in  macOS 12. I'll remove it from the preset interpreters for the next version.
