### ISSUE TITLE
Icon selected after loading profile is different to the one that was saved

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#205]
## Repro
1. Set the icon to the grey squircle
2. Save profile
3. Load profile
4. Icon changes to Platypus mascot

## Expected
- Same icon selected

## Actual 
- Selected icon is different

**Comment by sveinbjornt** [comment]
Is this in master or the 5.3 release?

**Comment by gingerbeardman** [comment]
Apologies, this is 5.3 release. I didn't realise it was so old.

I just build the latest code and it is indeed fixed.

Cheers!
