### ISSUE TITLE
cURL progress bar not shown in realtime

### ISSUE THREAD

**Issue by shadowsong91** [sveinbjornt/Platypus#206]
I used the script below to download something，progress was shown only if downloading was completed.
`curl -N -# -o app.zip "https://oss.npmmirror.com/dist/electron/15.3.0/electron-v15.3.0-darwin-x64.zip" 2>&1`
The `progress bar`(stderr) redirected to stdout.
How can I make progress shown in realtime？thx.

**Comment by sveinbjornt** [comment]
As noted in the documentation:

"this text view is not a full, interactive terminal session, and cannot be used to prompt for user input via STDIN. It does not support any of the standard terminal commands and cannot be used to display ncurses-based interfaces."

https://sveinbjorn.org/files/manpages/PlatypusDocumentation.html#text-window

**Comment by shadowsong91** [comment]
Sorry, I don't mean full functional terminal session.
cURL output progress to stdout by adding '\r' to line head.
By checking source code, I found output is split by '\n' only.
In this case, splitting by '\r' is necessary. That is maybe a little optimization.
