### ISSUE TITLE
PATH missing /usr/local/bin

### ISSUE THREAD

**Issue by ericbenfer** [sveinbjornt/Platypus#208]
When using Platypus to create an app from a shell script for some reason $PATH does not include /usr/local/bin

From terminal run `echo $PATH`
It will return `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` (There may be additional paths)

When running that same command via a Platypus shell script you only get `/usr/bin:/bin:/usr/sbin:/sbin`
It is missing `/usr/local/bin`

This can be verified with the attached PATH_test.sh
[PATH_test.sh.zip](https://github.com/sveinbjornt/Platypus/files/7507514/PATH_test.sh.zip)

**Comment by sveinbjornt** [comment]
As noted in the documentation:

https://github.com/sveinbjornt/Platypus/blob/master/Documentation/Documentation.md#how-does-my-script-access-the-users-shell-environment-eg-path

You can pass the -l flag to bash to inherit the user's environment.
