### ISSUE TITLE
How to customize the interpreter

### ISSUE THREAD

**Issue by btwise** [sveinbjornt/Platypus#211]
@sveinbjornt 
I want to package one of my php scripts into a command line binary file, but the php interpreter is not included in MACOS12, so I want to use and bundle a php interpreter and package it together. How to achieve this?

**Comment by prohtex** [comment]
@btwise to do this you would need to compile PHP as a static binary. Good luck with that one! If you pull it off please do let us know.

**Comment by cedrickp32** [comment]
@btwise I have the same problem. I have 4-5 apps built with php and now nothing is working on the new OS. I've been trying to include the php interpreter directly in the app without success. Did you found a way ?

**Comment by sveinbjornt** [comment]
Platypus now supports a relative path to the interpreter, which means that in theory you can include a static binary in bundled files and call it directly.
