### ISSUE TITLE
Running with the system env?

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#214]
I know this is more of a question of "how to use platypus" but I'm at a loss.

My shell script calls a node tool, but I am getting:

> "env: node: No such file or directory"

Whilst everything runs fine from terminal.

How should I set up my Platypus script to contain the correct env to allow access to install node, etc?

Thanks!

**Comment by sveinbjornt** [comment]
`bash -l` makes bash act as if it was invoked as a login shell. Should do the trick.

**Comment by gingerbeardman** [comment]
where should i put that? 

- as the script type?
- as the shebang in the script?
- somewhere else?

**Comment by gingerbeardman** [comment]
I've tried putting `-l` or `--login` as the only argument for the interpreter, but get this weird error.

No idea where the `-g` is coming from.

```
​/bin/bash: -g: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
```

**Comment by gingerbeardman** [comment]
OK, it's working.

The arg had stayed at the default `-arg` and not the `-l` that I had typed. Here's how that can happen: #215

**Comment by gingerbeardman** [comment]
Is there any reason why this workaround would stop working?

I'm puzzled, running Monterey 12.

![Screen shot 2022-07-31 at 19 04 47](https://user-images.githubusercontent.com/49612/182039447-1a9de0e6-21d9-4da4-b37c-e5326662268b.png)
5
