### ISSUE TITLE
Arg is not applied unless it loses focus

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#215]
When setting an Arg you need to let it lose focus, or it won't be applied. 

You can cause it to lose focus by:
- clicking away from the highlighted field
or
- pressing tab

But not by:
- clicking Apply

> Then you also have to regenerate the app, even if you have "Create symlink to script and bundled files" as the arg is not stored in those.

## Screen recording 
https://user-images.githubusercontent.com/49612/145290200-8529b298-788b-4083-b8aa-d8593abbbd43.mov

**Comment by sveinbjornt** [comment]
This is clearly a usability issue and a bug. Thank you for pointing it out. Will fix for next release.
