### ISSUE TITLE
Main script not executable when moved to another machine

### ISSUE THREAD

**Issue by oliv10** [sveinbjornt/Platypus#216]
I have written a python script, make it into script.app. Runs perfect on the machine it was created on (M1 Mac). Once I copy the application to another machine (Non-M1 mac) it doesn't work until I 'chmod +x' the script within the script.app on the new machine.

**Comment by oliv10** [comment]
Weird... Must have been a one off thing. I remade it, one with/one without root, seems to have fixed itself.

**Comment by oliv10** [comment]
I lied. More testing revealed its still not working.

**Comment by sveinbjornt** [comment]
What method are you using to copy it? UNIX file permissions might be lost if you're using a dodgy transfer method, e.g. sending via Apple's Mail without zipping first, etc.

**Comment by oliv10** [comment]
Pretty much just copying into OneDrive. I also tried copying to my NAS and then to another machine locally, that worked fine. I’ll try zipping it first to see if that solves the issue with OneDrive.

**Comment by oliv10** [comment]
I think you called it on the UNIX permissions changing. After zipping and then sharing through multiple different ways I have yet to run into the issue again. Thanks for then help!
