### ISSUE TITLE
Empty newlines aren't displayed correctly in text window

### ISSUE THREAD

**Issue by ad-si** [sveinbjornt/Platypus#218]
When I execute

```sh
echo "first"
echo ""
echo "second
```
the output is 

```txt
first
second
```

but it should be

```txt
first

second
```

It's the same with `printf`.

A workaround is to print a single space like so:

```sh
echo "first"
echo " "
echo "second
```

**Comment by sveinbjornt** [comment]
If I remember correctly, this has long since been fixed in master and will be part of the 5.3 release.
