### ISSUE TITLE
printing "LOCATION:https://example.com" as text when Web View set

### ISSUE THREAD

**Issue by richcouzzi** [sveinbjornt/Platypus#222]
The docs mention when Interface is set to "Web View", printing the location statement should load the URL in question. Instead, my Web View prints it out as text. What am I doing wrong?

![image](https://user-images.githubusercontent.com/1315560/154345287-cbeea40f-78ef-48f7-b0f9-0d68efe5f37b.png)

![image](https://user-images.githubusercontent.com/1315560/154344703-fed7f316-2470-4496-85cc-f86d3ecd9083.png)

```
#!/bin/sh

echo 'LOCATION:http://example.com\n'
```

**Comment by adamphetamine** [comment]
I'm having this issue too. 
Did you get this sorted @richcouzzi ?

**Comment by richcouzzi** [comment]
> I'm having this issue too. Did you get this sorted @richcouzzi ?

No, no luck with using the LOCATION string as the docs describe. I did find a good-enough-for-my-purposes workaround; Just write single line, which is a <meta> tag to redirect:

`#!/bin/sh

echo '<meta http-equiv="refresh" content="0;url=index.html" />'`

where index.html is a bundled file, but this approach works for external destinations too:

`#!/bin/sh

echo '<meta http-equiv="refresh" content="0;url=https://example.com" />'`

Another workaround I explored was using `<iframe style="height:100vh; width:100vw; border:none; overflow:auto;" src="index.html"></iframe>` which works as expected for bundled files, but fails for some (most) external URLs as sites can and do block loading in iframes.

**Comment by sveinbjornt** [comment]
This is a bug in Platypus 5.3 and has been fixed in master. Thanks for the feedback.
