### ISSUE TITLE
[Feature Request] - CLI

### ISSUE THREAD

**Issue by sgates** [sveinbjornt/Platypus#227]
I'd love to be able to automate the creation of apps as part of a CI/CD process - is there a CLI version available? Maybe I'm just missing a better way?

**Comment by sveinbjornt** [comment]
Platypus includes a command line tool for this very purpose:

https://sveinbjorn.org/files/manpages/PlatypusDocumentation.html#show-shell-command

**Comment by sgates** [comment]
@sveinbjornt I totally missed that in the docs. Sorry for the trouble. Thanks for supporting such a great app over the years!
