### ISSUE TITLE
ModuleNotFoundError thrown, but module is included

### ISSUE THREAD

**Issue by finnhewes** [sveinbjornt/Platypus#231]
<img width="1286" alt="Screen Shot 2022-08-24 at 6 05 48 AM" src="https://user-images.githubusercontent.com/98352998/186311724-f8682943-3026-4d08-8e30-ac6290c10c47.png">
<img width="1429" alt="Screen Shot 2022-08-24 at 6 04 38 AM" src="https://user-images.githubusercontent.com/98352998/186311734-30e488ee-f2dc-4c8d-95dd-8eaf470a0071.png">

I'm trying to run a relatively simple password manager with a gui, and keep running into the same error message here. I have the cryptography module installed locally on my laptop, and it also appears in the package contents of the app outputted by Platypus. Any ideas on what's causing this issue?

**Comment by sveinbjornt** [comment]
This is a Python import error and doesn't really have anything to do with Platypus. Make sure what you're trying to import fram is in the import search path. Your shell settings, e.g. ENV stuff, will not be shared by the Platypus application. Closing.
