### ISSUE TITLE
No Support for Apple M1?

### ISSUE THREAD

**Issue by paulhundal** [sveinbjornt/Platypus#234]
Is there a plan to support binaries that can run on apple silicon m1?

**Comment by actuallymentor** [comment]
What do you mean by this? I'm on an M1 and can open Platypus just fine. The brew version is outdated though and causes issues. You should manually download it.

**Comment by chenrui333** [comment]
Yeah, the latest release build had some issue, but it should be covered now by [this](https://github.com/Homebrew/homebrew-core/pull/109580)

**Comment by sveinbjornt** [comment]
The issues with the last release have been fixed in version 5.4.1.
