### ISSUE TITLE
app created with platypus asks for password

### ISSUE THREAD

**Issue by covici** [sveinbjornt/Platypus#235]
Hi.  I created an app using platypus and when I try to open it, it asks for my password, as though it wanted to make changes.  I did give it full disk access, is there something else I need to do to avoid it asking for a password, as I want to use cron to run this daily?

**Comment by actuallymentor** [comment]
You probably accidentally checked the "run with root privileged" checkbox?

**Comment by covici** [comment]
It was not an accident, I wanted it to run that way, any way to do
that and not have it ask for a password?

On Sun, 18 Sep 2022 16:27:28 -0400,
Mentor Palokaj wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> You probably accidentally checked the "run with root privileged" checkbox?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/sveinbjornt/Platypus/issues/235#issuecomment-1250381017
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***

**Comment by actuallymentor** [comment]
If you run as root, you need a password.

**Comment by covici** [comment]
What if you change the app so it is owned by root, will that help any?

On Mon, 19 Sep 2022 06:12:07 -0400,
Mentor Palokaj wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> If you run as root, you need a password.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/sveinbjornt/Platypus/issues/235#issuecomment-1250825553
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***

**Comment by sveinbjornt** [comment]
There is no way for Platypus to run the script with root privileges without asking for a password. That's simply how Apple's Security API works.
