### ISSUE TITLE
Progress Bar text settings incorrectly applied in Dark Mode

### ISSUE THREAD

**Issue by toobuntu** [sveinbjornt/Platypus#242]
I tried to set custom foreground and background colors for a progress bar text box (Solarized Dark, FWIW). They seem to work fine when the macOS System Settings are for Light Mode. However, they are not honored when in Dark Mode on macOS 13.2.

Light Mode example:
![Screenshot 2023-02-07 at 5 45 53 PM](https://user-images.githubusercontent.com/674390/217308819-f7b7cbca-b1db-408b-a5ab-5b0b0866083e.png)

Dark Mode example, same app:
![Screenshot 2023-02-07 at 5 46 36 PM](https://user-images.githubusercontent.com/674390/217308973-78fff6b2-d2ef-43c6-b115-bedbb3864171.png)

The app was generated on the command line by using the following flags for the color selection: `--text-foreground-color '#839496'  --text-background-color '#002B36'`

**Comment by sveinbjornt** [comment]
All specified text colors are inverted in Dark Mode. This is expected behaviour.
