### ISSUE TITLE
Collor Text Window

### ISSUE THREAD

**Issue by chris1111** [sveinbjornt/Platypus#244]
Collor Text Window change in dark mode macOS Ventura 13.2
In Light Mode collor is OK 

See Picture

![Screenshot 2023-02-10 at 6 00 00 PM](https://user-images.githubusercontent.com/6248794/218218574-c715c48f-8dab-443c-8846-c3d13a1ab1aa.png)

App in Light Mode collor is OK

![Screenshot 2023-02-10 at 6 03 12 PM](https://user-images.githubusercontent.com/6248794/218218833-a336cdbb-c51f-49f3-939b-249c1705c53c.png)

App in Dark Mode collor change
![Screenshot 2023-02-10 at 6 02 46 PM](https://user-images.githubusercontent.com/6248794/218218747-95c7ad5d-dea3-40fc-a717-56823cc4315c.png)

**Comment by sveinbjornt** [comment]
This is expected behaviour. The colors of the text view are inverted in dark mode.

**Comment by sveinbjornt** [comment]
It was something a lot of people requested so it was added in 5.2 or 5.3 (don't remember).

**Comment by chris1111** [comment]
> It was something a lot of people requested so it was added in 5.2 or 5.3 (don't remember).



Ok 
Thanks
