### ISSUE TITLE
Pressing undo in script editor loses all changes

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#251]
1. open script editor
2. make multiple changes
3. press Cmd+Z

Expected
- most recent change is undone

Actual
- all changes are undone! 😢

**Comment by sveinbjornt** [comment]
I don't really recommend using the built-in editor. It's very primitive.

**Comment by gingerbeardman** [comment]
Thanks! I didn't know there was an option to use anything else.

This has solved it for me:
![Screen shot 2023-05-13 at 12 36 52](https://github.com/sveinbjornt/Platypus/assets/49612/af629763-2547-4f07-81a8-41a481210d59)
