### ISSUE TITLE
Create a default browser?

### ISSUE THREAD

**Issue by dzg** [sveinbjornt/Platypus#253]
I'm trying to use Platypus to make an app from this AppleScript:
```
on open location theURL
	tell application "Google Chrome"
		make new window
		activate
		set URL of active tab of first window to theURL
	end tell
end open location
```
... which I want to make the "Default Web Browser"...

<img width="469" alt="image" src="https://github.com/sveinbjornt/Platypus/assets/466557/4f8aa2f0-d4b9-4c53-8ca1-c7437c679634">

... so that when I open a link outside of Chrome, it opens in a **New Window**.

So I followed the instructions at https://stackoverflow.com/questions/42605571/how-to-register-a-python-script-with-mac-osx-as-a-web-browser ...
<img width="242" alt="image" src="https://github.com/sveinbjornt/Platypus/assets/466557/30679e87-a2c1-41f8-b94e-8633825ea509">
but not sure what to put for URI scheme. I tried `http` but after running, it did NOT show up as possible default browser.

**Comment by gingerbeardman** [comment]
I can't help with this, but I use Default Browser app to take care of this issue for me. https://defaultbrowser.app

**Comment by dzg** [comment]
@gingerbeardman Thanks – but that does not allow to force a new window AFAICT (which is my whole purpose here)

**Comment by gingerbeardman** [comment]
Ah, I see now, apologies.

So every link from outside of Chrome will open in its own window?

**Comment by gingerbeardman** [comment]
Here is how I managed to get it to show as a browser: [Browsy.platypus.zip](https://github.com/sveinbjornt/Platypus/files/11559141/Browsy.platypus.zip)

![Screen shot 2023-05-24 at 22 02 36](https://github.com/sveinbjornt/Platypus/assets/49612/cb4d29ed-e5ff-48f7-b7cd-6e82e7516c23)

I have not tested whether the AppleScript you're using works. 

Here is the new app showing up in Default Browser.

![Screen shot 2023-05-24 at 22 02 02](https://github.com/sveinbjornt/Platypus/assets/49612/d8931d64-1fa1-4ccc-82b8-9a85cc6f7cca)
