### ISSUE TITLE
configure Info.plist

### ISSUE THREAD

**Issue by orefalo** [sveinbjornt/Platypus#254]
Thank you fro this great app -
 
If I may ask a quick question, is it possible to customize the generated Info.plist?

I am using universalJavaApplicationStub and it reads JVM attributes from there...

**Comment by sveinbjornt** [comment]
Yes, you can edit the Info.plist in a created app just like you can in any other app. It's in Contents/Resources/Info.plist as expected.

**Comment by orefalo** [comment]
it's in binary format.

**Comment by sveinbjornt** [comment]
You can open and edit binary plists with Xcode and a number of third party plist viewers such as PlistEdit.

Then there's the plistutil command line tool, which ships with macOS and can convert between binary and XML (see "man plistutil").
