### ISSUE TITLE
Disable UTIs from the command line

### ISSUE THREAD

**Issue by oashour** [sveinbjornt/Platypus#257]
Hello,

Is there a way to disable UTIs when using the command line? If I pass the `--suffixes` flag, they will be correctly added to the generated profile/app, but the default UTIs `public.item` and `public.folder` will still be there. 

I don't understand UTIs too much, but I need to open two specific extensions (plain text files) associated with certain scientific software that don't have any discernable UTIs (`dyn.<random string>` when dragged into the GUI). Removing the default UTIs from the GUI and using the suffixes is the only way I've got the app to work, but I can't get rid of the UTIs from the command line.

Thanks!

**Comment by sveinbjornt** [comment]
Specifying UTIs as an empty string should work, e.g.`platypus --uniform-type-identifiers ""`
