### ISSUE TITLE
Drop targets do not work with “Remain running after initial execution” off

### ISSUE THREAD

**Issue by kopischke** [sveinbjornt/Platypus#26]
I have found my app will not function when “Remain running after initial execution” is not checked and the app is meant to be used as a drop target (i.e via static drop, or via services). Obviously, this is very hard to examine, as any output disappears with the app, but short glimpses of output makes me suspect the script actually needs to runs twice on drop targets: once empty, once with the NSPBoard parameters, which would explain the erratic behavior (as Platypus would quit after the first run).

*Platypus 4.8, OS X 10.9.0*

**Comment by felixdreinulldrei** [comment]
This bug still exists.  In my case I'm drag and dropping an url from a browser onto my  app. 
If “Remain running after initial execution” is checked, the app  does pass the right url (text string)
to the bash script and everything will work fine.
If “Remain running after initial execution” is unchecked, the app does pass i.e "-psn_0_3498838"
to the script.
BTW. dragging files onto my apps filepath are  passed as $2 arguments, dragging text onto my apps the snippets are passed as $1 arguments. Is this a bug?

**Comment by sveinbjornt** [comment]
This is fixed in latest master. Closing...
