### ISSUE TITLE
Cannot run Platypus on MacOS Sonoma

### ISSUE THREAD

**Issue by abid76** [sveinbjornt/Platypus#267]
Hi when I try to run the latest Version 5.4.1 on Sonoma 14.2.1 I get an error that it cannot be opened as MacOS cannot look for malicous code in it.

<img width="303" alt="Bildschirmfoto 2024-02-06 um 14 26 08" src="https://github.com/sveinbjornt/Platypus/assets/34437604/33f46bca-7f53-4d03-a395-eb6709bc01fb">

Is there anything I can do about it? Or is Platypus currently not compatible with Sonoma?

**Comment by abid76** [comment]
Follow-up: when running Platypus by CRTL-click it finally worked.

**Comment by sveinbjornt** [comment]
This is expected behaviour. Platypus is Developer ID signed, but not notarized by Apple.
