### ISSUE TITLE
Improvement: option to pass NSPBoardText on STDIN

### ISSUE THREAD

**Issue by kopischke** [sveinbjornt/Platypus#27]
This would greatly simplify handling textual input in languages that have good STDIN  support (specifically, I’m thinking of Ruby’s ARGF). Right now, scripts have to loop over input and apply heuristics to differentiate between text content (which can legitimately contain file paths not to be treated as input) and a set of file paths parameters.

**Comment by sveinbjornt** [comment]
Implemented in master.
