### ISSUE TITLE
Where are the advanced settings

### ISSUE THREAD

**Issue by Squirreljetpack** [sveinbjornt/Platypus#277]
I'm trying to create an app to handle a URI scheme, but I cannot find the advanced section anywhere. Not a huge deal because the stuff can be done manually/with cliI but I'm kind of confused. Are they still here? Or only for the cli?

**Comment by sveinbjornt** [comment]
Check the checkbox "Accept dropped items" and press the Settings button that appears next to it. There you should be able to configure the URI schemes.
