### ISSUE TITLE
Menulet text obscured in Yosemite's Dark Mode

### ISSUE THREAD

**Issue by brunerd** [sveinbjornt/Platypus#44]
The text area of a menulet renders as a blurry/semi-opaque area (with no text visible at all) in Yosemite's Dark Mode. Switching back to normal mode, the menulet text renders correctly.

**Comment by sveinbjornt** [comment]
Status menu items can no longer have both a title and an icon as of Yosemite. I have therefore disabled that option, leaving the choice between an icon OR a title.
