### ISSUE TITLE
Wrapping a simple Python script that gets files as argument(s) and uses raw input

### ISSUE THREAD

**Issue by novoid** [sveinbjornt/Platypus#45]
Hi!
I failed at multiple attempts to wrap a Python script into an App using Platypus :-(

My script is available at https://github.com/novoid/filetags - it gets a list of files as arguments and then prompts for tags that gets added to the file names (in interactive mode).

Not that hard to wrap I thought.

However, first I had to learn that raw_input() method of Python does not work when wrapped with Platypus: 
http://stackoverflow.com/questions/17281607/python-to-mac-app-eoferror-caused-by-raw-input
http://stackoverflow.com/questions/4711589/python-raw-input-causing-eoferror-after-creating-app-with-py2app

Then I tried to wrap filetags.py within a simple wrapper shell script. The only way I could find to start a Terminal with the script was:

```
osascript -e 'tell app "Terminal" to do script "filetags --verbose ${@}"'
```
Well this did not work since the parameter ${@} does not get replaced by the shell arguments because I have to use single ticks for the oascript argument and double quotes for the argument within the oascript argument.

Maybe I did not think of any simple solution for this issue. For now, I have to give up and cry for help :-)

So, what do you suggest how I can wrap my script so that I am able to send file(s) to it and still being able to enter strings interactively.

Thanks!

**Comment by sveinbjornt** [comment]
Platypus apps are not an interactive Terminal. They merely capture script output and present it in a graphical user interface. You cannot use sudo or raw_input or anything that requires input from the user. This is clearly stated in the documentation. Closing.
