### ISSUE TITLE
Disable smart quotes and dashes within embedded script editor

### ISSUE THREAD

**Issue by tjnycum** [sveinbjornt/Platypus#48]
Smart quote and dash replacement is an option in OS X System Preferences. It can be helpful when typing text for humans, but generally frustrates writing scripts because most, if not all, parsers don't recognize the replacement characters as equivalent to the ones typed. The system option seems to affect the script editing text box within Platypus.

To reproduce:
Enable "Use smart quotes and dashes" in System Preferences > Keyboard > Text.
Open Platypus.
Select Bash as Script Type.
Click "New" under the Script Path box.
Delete the single quote at the end of the "Hello, World!" string.
Press the double/single quote key on the keyboard to try to retype it.

If you look closely, after a moment it will replace the plain single-quote/apostrophe character with one that curves to the left (closing). If you save and try to use that script, you'll get a syntax error from bash. (An easier "smart" replacement to see is the replacement of two adjacent hyphens with an "en" dash.)

If it's possible to opt out of this functionality in a particular OS-X–standard (Cocoa?) text box despite it being enabled at the system level, would you please do so?

**Comment by sveinbjornt** [comment]
This has been fixed on the current branch, and will be part of the improvements for the next version of Platypus. That being said, the built-in text editor is never going to be good for anything but very small scale stufff. Platypus is not a text editor and shouldn't aim to be.

**Comment by tjnycum** [comment]
Thanks, and I agree.

**Comment by sveinbjornt** [comment]
Verified as fixed in master, will be part of the changes and improvements in version 4.9.1
