### ISSUE TITLE
The default bundle identifers broke in latest version when using cmdline tool

### ISSUE THREAD

**Issue by chdiza** [sveinbjornt/Platypus#50]
It used to be that passing `-u Username` to the command line  tool would have the bundle identifier of the resulting app be set to `org.Username.Appname` (unless the user overrode this with `-I`).

In the latest version of platypus, it instead results in a bundle ID of `(null)Appname`.

**Comment by sveinbjornt** [comment]
Well spotted, thanks for letting me know. I'll get this fixed in the next release, which shouldn't be far off.

**Comment by sveinbjornt** [comment]
Fixed in master. Author name argument is now used to generate default bundle identifier in command line tool.
