### ISSUE TITLE
Audio output not working?

### ISSUE THREAD

**Issue by jkono** [sveinbjornt/Platypus#52]
It doesn't look like commands that can produce audio feedback (e.g. `ping -a <some-ip-address>`) aren't actually producing sound.  Is that the intended behavior?

**Comment by sveinbjornt** [comment]
Platypus does not actually create a terminal session. The scripts are executed either using NSTask or Apple's Security Framework's AuthorizationExecuteWithPrivileges(). Features that require a terminal session, such as prompting for STDIN or beeping will not work.
