### ISSUE TITLE
Choose arguments

### ISSUE THREAD

**Issue by YocYoc** [sveinbjornt/Platypus#54]
Is there a way to interact with some arguments for the shell script you want to wrap ? In my script, I would like to choose the argument I want to pass to the script at the time I launch the application, instead of making multiple applications.
exemple : imagine I want to wrap "ls". I could make two applications, one for "ls -a" and one for "ls -l", but I would prefer choosing at launch time if I want to do "ls -l" or "ls -a" from the same application.

**Comment by jkono** [comment]
I ended up using Pashua (https://www.bluem.net/en/mac/pashua/) to create a dialog to allow options to be selected.  A script to build the Pashua window and assemble the selected options into a command string will be needed, and that's what will be run by Platypus.  If you want a stand-alone app bundle, the Pashua executable can be included with the script in the Platypus-created bundle.
