### ISSUE TITLE
Feature request - run script before exit

### ISSUE THREAD

**Issue by voltagex** [sveinbjornt/Platypus#57]
Don't know if this is possible, but bash scripts run inside Platypus don't get a chance to run a function specified by trap EXIT - so my cleanup function never runs.

Would it be possible to allow setting a script to run before exit or change the way Bash scripts are run? Is a signal sent to the script when the app is closed?

**Comment by sveinbjornt** [comment]
Assuming you're not using "Run with Administrator Privileges", scripts are run using NSTask:

    https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTask_Class/#//apple_ref/occ/instm/NSTask/terminate

If the app is quit or the task is cancalled before the script is done executing, the script task is terminated using [task terminate].  This sends SIGTERM.

**Comment by voltagex** [comment]
Ah. I am running using Administrator - what changes in that case?

**Comment by sveinbjornt** [comment]
Basically, if Administrator mode is enabled, the script is run via AuthorizationExecuteWithPrivileges() in Apple's Security API. There is no method provided to terminate tasks invoked using this function.  However, authenticated execution is something that I've been meaning to look better into. Will put your issue on the roadmap for the 5.1 release.

https://github.com/sveinbjornt/Platypus/commit/e5cb3c033816a283f3184cafee60aabacd48afc5

**Comment by jasonrwang** [comment]
Is this (incl #46) still the case on Catalina? Quiting (CMD+Q) on my compiled app (_not_ running in root) doesn't seem to run the code in `trap code SIGINT SIGTERM` (I tried with `15` instead of `SIGTERM` as well). Running the script directly in Terminal and then CNTL+C successfully runs the trap code though.
