### ISSUE TITLE
Not possible to edit MainMenu.nib after creation

### ISSUE THREAD

**Issue by cosmonawt** [sveinbjornt/Platypus#59]
I tried different settings, also unchecking 'Optimize Application'. The result was always the same: I could never edit the MainMenu.nib file after I created the application.
I then copied the code from MainMenu.xib here on GitHub, but even without any edits there would either show no window at all, or no text inside it.
It seems the MainMenu.nib inside the Platypus.app (which I suppose is just copied) is already compiled and thus can not be edited afterwards.

Also, I have three little feature requests (which would make my wanted edits obsolete):
- Option to edit background transparency to match the 'El Capitan' Look and Feel
- Make textview wider (as wide as the window itself) for the same reason: Look and Feel
- Enable 'Close' Button in the top left which quits the app, and replace the 'Quit' button

**Comment by sveinbjornt** [comment]
This is a bug, the MainMenu.nib file shipping with Platypus should be in an editable state.  I'll just go ahead and fix that for you real quick.

**Comment by cosmonawt** [comment]
Thank you very much. I would much appreciate it, if you could tell me when the changes are done and where I can find them then.

**Comment by sveinbjornt** [comment]
OK, this is now fixed in master.

**Comment by sveinbjornt** [comment]
Just released Platypus 5.1, which fixes the issue.
