### ISSUE TITLE
Can't run ffmpeg from within droplet app.

### ISSUE THREAD

**Issue by weavermedia** [sveinbjornt/Platypus#60]
I've got a simple audio converter script running in Ruby and wrapped it as a droplet.

When I trace the system log output the script breaks at the call to ffmpeg:

```
`ffmpeg -ss 0 -i input.wav -t 5 output.wav`
```

with this:
My App [9097]: Appending output: "/Users/danielweaver/Desktop/input.wav"
My App [9097]: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Does the Ruby script have access to `/usr/local/bin` in order to run ffmpeg?

**Comment by weavermedia** [comment]
FWIW, a call to `mkdir` earlier in the script works fine.

**Comment by sveinbjornt** [comment]
I take it you're running the latest release (5.0)?  This is a bug in that release which has now been fixed on the master branch, and is related to parsing text output in modes other than Text Window and Progress Bar.

**Comment by weavermedia** [comment]
Excellent! Is there a release date planned for the next version? Alternatively, how can I build from the source?

**Comment by sveinbjornt** [comment]
There's a build_release.sh script in the root of the source tree which should do the trick. Can also be done in XCode.

**Comment by weavermedia** [comment]
Fantastic, thanks.

**Comment by sveinbjornt** [comment]
Just released Platypus 5.1, which fixes the issue.
