### ISSUE TITLE
Sparkle Feed Vulnerability

### ISSUE THREAD

**Issue by seansgm** [sveinbjornt/Platypus#61]
Due to the [Sparkle Feed Vulnerability](https://vulnsec.com/2016/osx-apps-vulnerabilities/) can we expect a patched update with a https feed and an update to the patched sparkle framework?

Thanks

**Comment by sveinbjornt** [comment]
Thanks for the pointer, will update Sparkle and look into setting up HTTPS on the server...

**Comment by seansgm** [comment]
From what I understand you'd need https for 10.11 anyway.  I'm reading that OS X 10.11 deprecated HTTP and blocks updates unless you use HTTPS or disable App Transport Security.  Thanks for being so prompt.

**Comment by sveinbjornt** [comment]
Platypus currently has App Transport Security disabled in the Info.plist.

**Comment by seansgm** [comment]
Which will mean it will work on 10.11, but at the expensive of security though, right?

**Comment by sveinbjornt** [comment]
Yeah. There's no way to keep updates working without disabling ATS unless I get the server to support https. I'ts just a home server of mine, shouldn't take long if I get a self-signed certificate.

**Comment by jwittkoski** [comment]
You might want to look at Let's Encrypt (https://letsencrypt.org/) to get a real certificate that's free (and trusted by OSX for at least 10.10+).

**Comment by seansgm** [comment]
I don't suppose you are any closer to releasing a patched version are you?

**Comment by sveinbjornt** [comment]
The latest version of Sparkle has been added to master. Now I just to get around to setting up HTTPS on the server.

**Comment by pirate** [comment]
@sveinbjornt just [donated](http://sveinbjorn.org/donations) $15 because Platypus rocks, :) of course you're free to use it however you want, but ......

Maybe you could check out a cert like this cheap $9/year one if you have some spare time on a weekend: https://www.namecheap.com/security/ssl-certificates/comodo/positivessl.aspx  (letsencrypt is great, but commercial certs are still faster to set up).

**Comment by sveinbjornt** [comment]
Thanks very much for the donation! I've been meaning to set up https for a while now, it's not really a question of cost, more a question of getting around to doing the admin stuff necessary to set it up. Soon!

**Comment by tewe** [comment]
I think GitHub can host your updates, or at least the feed. With HTTPS of course.

**Comment by sveinbjornt** [comment]
OK, I've set up HTTPS on the server. All future updates will be served over SSL. ATS enabled for all future builds.
