### ISSUE TITLE
Script behaves differently when run as Platypus app

### ISSUE THREAD

**Issue by bwagner** [sveinbjornt/Platypus#62]
I'm using the command line platypus (current branch c836575d3fc6931945696c6b9ed0e45f4a798fed) on OSX 10.11.3 (El Capitan)

My script works fine when run by itself (toggles Internet Sharing) but stops prematurely when run as a platypus app.

You can download the development directory from here: http://xmlizer.net/internetSharing.tgz. To build the app, call `make` in the top level directory. To run the app, call `make run`.

Thank you

**Comment by sveinbjornt** [comment]
What's the output? Are you getting any error messages?

**Comment by bwagner** [comment]
when I run `./internetSharing.pl` in the development directory, I don't get any output. When I run the platypus app with `make run` the output is `open InternetSharing.app`, which obviously comes from the Makefile. If I inhibit output by preceding the Makefile-command like so `@open $(TARGET)`, there's no output.

The app stops always at the same moment when running as a platypus app: When the Sharing dialog has just opened.

**Comment by sveinbjornt** [comment]
When I run your app (macOS Sierra 10.12), I get the following:

    348:888: execution error: System Events got an error: osascript is not allowed assistive access. (-1728)
    failed to close osascript: at /Users/sveinbjorn/Desktop/internetSharing/InternetSharing.app/Contents/Resources/script line 46.

I don't know what exactly is going on there, but I'm pretty sure it has nothing to do with Platypus.

**Comment by bwagner** [comment]
How exactly do you run it to get that output?

**Comment by sveinbjornt** [comment]
cd InternetSharing.app/Contents/MacOS
    ./InternetSharing

**Comment by bwagner** [comment]
Interesting... that works just fine in my case (10.11.6 (El Capitan)) with no output.
Do you get that output in the terminal?
It's when I run the app from the Finder by selecting it and then typing Cmd-O (or double-clicking it) that the app halts: When the Sharing dialog has just opened.

**Comment by QAZach** [comment]
Don't know if this is still relevant, the `error: osascript is not allowed assistive access.` is because you need to give accessibility permissions to the script editor.
