### ISSUE TITLE
How to configure Platypus-generated app to accept links dragged out of webpages?

### ISSUE THREAD

**Issue by bwagner** [sveinbjornt/Platypus#63]
I'm developing a Droplet on `OS X 10.11.3` that accepts links (urls) dragged directly out of webpages. The underlying script works fine when run from `Terminal`, since `Terminal` accepts _everything_ that's dropped onto it: I simply type `myUrlWrangler.pl` followed by a space in `Terminal`, and then drop the url into `Terminal`.

However as a `Platypus` app it doesn't accept urls that I drag from a webpage or from the address bar onto the droplet. I've tried quite a few Uniform Type Identifiers:

```
public.item
public.data
public.content
public.html
public.url
public.file-url
public.url-name
com.apple.webarchive
```

including no UTI at all, just the Suffix `*` and enabled `Accept dropped text`, to no avail.

The [Platypus docs](http://www.sveinbjorn.org/files/manpages/PlatypusDocumentation.html#41) say, 

> You can drag files from the Finder into the suffix or UTI list to add their respective suffix/UTI.

However, when I drop a URL from a webpage onto the UTI list, nothing happens (which may be a hint why it doesn't work with the generated app either).

I found, by adding the UTI `com.apple.web-internet-location` that at least URLs dragged from the _address bar_ are accepted.

There's an [article](http://stackoverflow.com/questions/8017468/ios-document-file-type-associations-wildcard-uti) where the author analysed `Info.plt` for the `Dropbox` app to reveal how it allows to receive everything, namely with the UTIs `public.data`and `public.content`. Yet, even this combo does not enable my `Platypus app` to receive URLs.

How can I configure my `Platypus`-generated app to accept links dragged out of webpages?

**Comment by tewe** [comment]
Which browser are you dragging out of? They offer different representations of addresses. You can debug using [ClipboardViewer](https://developer.apple.com/library/mac/samplecode/ClipboardViewer/Introduction/Intro.html).

**Comment by sveinbjornt** [comment]
You should be able to fix this by enabling the app as a Service under Drop Settings. Let me know if that works.
