### ISSUE TITLE
[FR] undo script

### ISSUE THREAD

**Issue by larryy** [sveinbjornt/Platypus#66]
Feature Request:  It would be extremely convenient and useful if the generated app's Undo menu item could invoke a second script.

If the main script runs to completion and terminates there obviously cannot be any saved state in memory for the undo, but at least for the application I have in mind, it would be easy to manage the little bit of necessary state through the filesystem.  And I do have an immediate use for this feature, if and when.

**Comment by sveinbjornt** [comment]
That's an extremely narrow use case, and it's deeply unclear to me whether it's a good idea, for UX reasons. Closing.
