### ISSUE TITLE
CLI version does not add bundled files to bundle when called in the 'classic command line args' style (i.e. not with a Platypus profile)

### ISSUE THREAD

**Issue by themasterchef** [sveinbjornt/Platypus#67]
Expected behaviour:

When presented with files or folders to bundle, both CLI and GUI clients bundle them, and the bundling list is preserved when you write out a platypus profile.

Actual behaviour:

When presented with files or folders to bundle...

- GUI client bundles them
- CLI client bundles them when invoked with -P (platypus profile)

But when CLI client is invoked with the 'classic command line args' form it does not complete all steps of bundling. It checks the file exists, but never gets round to adding it to the bundle.

If you pass files to bundle, and render a platypus profile like this

    platypus --bundled-file '/opt/bar' --generate-profile 'foo.sh'

When you inspect the foo.sh.platypus profile you will see that BundledFiles is an empty array:

    ...
    <key>BundledFiles</key>
    <array/>
    ...

 so clearly this information has been lost somewhere after the initial existence check.

I have more information if you need it.

Platypus CLI v5.1 installed from Homebrew on OS 10.11.4

**Comment by tewe** [comment]
The problem seems to be line 199:

    [properties[AppSpecKey_BundledFiles] addObject:fp];

properties is a dictionary that doesn't have that key, unless it's been copied over from a profile. Otherwise the array needs to be created first.

**Comment by sveinbjornt** [comment]
Fixed in master.
