### ISSUE TITLE
bash based app runs two times when dropping text snippets (vers 5.1)

### ISSUE THREAD

**Issue by felixdreinulldrei** [sveinbjornt/Platypus#68]
If dropping a file onto an app everything works fine.
But if dropping a textsnippet onto an app, the app is executed two times within one run.
Like a loop. But only two times.
On its 1st run stdin will show empty input.
On its 2nd run  it will overwrite the textwindows content and show the dropped text from stdin.
Here is a test script to to see the issue. When running also watch the date/time output in the textwindow.
But please test it multiple times. At the very very 1st run of the app, right after creating, it seems to work for only one time.

---
# !/bin/bash

text=$(cat)
date
echo 'Hello, World'
echo 1 $0
echo 2 $1
echo 3 $text
sleep 5

---

Running on OS X 10.10.5

**Comment by tewe** [comment]
Please include the Platypus settings you used.

**Comment by sveinbjornt** [comment]
Platypus apps run the script once when the application is launched, and again whenever you drop text on the app. So you can check whether there's something in stdin, and if not, you know that the script is not being launched as a response to a drag event.
