### ISSUE TITLE
Erroneous warning "not a valid bundle identifier"

### ISSUE THREAD

**Issue by tewe** [sveinbjornt/Platypus#71]
The CLI says `Warning: 'public.avchd-collection|public.iso-image' is not a valid bundle identifier` but everything works fine.

Turns out it's calling `BundleIdentifierIsValid` with the raw `--uniform-type-identifiers` argument, but that function only support a single identifier.

Also users may confuse the message for the identifier of the app they're about to create, so it might be good to mention UTI somewhere.

**Comment by sveinbjornt** [comment]
Fixed in master, fix will be released in 5.2. Thank you for pointing out this silly mistake.
