### ISSUE TITLE
CFBundleTypeRole omitted

### ISSUE THREAD

**Issue by tewe** [sveinbjornt/Platypus#72]
Platypus doesn't seem to set a `CFBundleTypeRole` when writing `Info.plist`. Everything still works, but the console log is spammed with:

    NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.

**Comment by sveinbjornt** [comment]
Yeah, I took it out, didn't think it mattered. Best put it back in then...
