### ISSUE TITLE
Dropped items behavior in 5.1 with more than 1 UTI

### ISSUE THREAD

**Issue by mikemcduffie** [sveinbjornt/Platypus#73]
Conditions: add 2 document specific UTIs (e.g. public.zip-archive and public.rar-archive) and delete public.item (to prevent passing any file type and invalidating the reason for adding 2 UTIs)

Behavior: The app relaunches for every file type (zip, rar and folder) in the Finder selection. 

Is this the expected behavior? I expected one launch of the app with all the dropped items. 

I can all the items in one launch by re-adding public.item but all dropped items are passed to the script (no filtering by document UTI).

It also appears that the "accept dropped items" is just a filter to the script and there is no user feedback in the OS GUI that a file type is not supported. Looking at the plists, this seems to be the designed behavior as these AppSettings.plist rather than the standard Info.plist. I just wanted to confirm that the standard OS behavior is not supported.

**Comment by tewe** [comment]
I can't reproduce this. My debug script is just launched once:

    #!/usr/bin/python

    from __future__ import print_function

    import os
    import sys

    with open(os.path.expanduser('~/%i.txt' % os.getpid()), 'a') as f:
        print("parent process id", os.getppid(), file=f)
        print("current process id", os.getpid(), file=f)
        print("command line arguments", sys.argv, file=f)

But files of an unsupported type are indeed removed from the argument list, with no feedback. I don't know if it's the OS or Platypus doing it.

Also `public.rar-archive` wasn't registered on my machine, only `com.rarlab.rar-archive`.

**Comment by mikemcduffie** [comment]
Thanks for the reply. I filed a bug report with Apple as I noticed that it was happening on more than one app a  week or two later. Sorry about not posing an update. I am curious why you're not seeing it as I tested on two different Macs with 10.11.5 and both had the issue.

**Comment by sveinbjornt** [comment]
I can't reproduce this. I would rebuild the Launch Services database if I were you. Let me know if it continues on vanilla systems.
