### ISSUE TITLE
Suffix field inactive

### ISSUE THREAD

**Issue by tewe** [sveinbjornt/Platypus#76]
1. launch Platypus (e.g. 5.1 on 10.11.6)
2. click Clear (for good measure)
3. check Accepts dropped items
4. click the Settings button that appears

At this point the label of the suffix list is grey, and the buttons inactive!

5. uncheck Accept dropped files
6. re-check Accept dropped files

Now the plus button is active!

7. click Restore Defaults

Now it's inactive again!

This can't _all_ be intended behavior ;)

**Comment by sveinbjornt** [comment]
Well spotted, that is in fact a bug. Thank you for pointing it out. Fixed in master.
