### ISSUE TITLE
-f or --bundled-file in Command Line Tool doesn't work

### ISSUE THREAD

**Issue by icespeech** [sveinbjornt/Platypus#78]
Version: Platypus 5.1
Platform: Mac OS X 10.10
Description: When I was using the command line tool in Platypus to create a new bundle, the -f (or --bundled-file) argument won't copy the file(s) I listed to the Contents/Resources folder. But the GUI version App works well.

**Comment by sveinbjornt** [comment]
Now fixed in master.
