### ISSUE TITLE
Installer icon changes color once created

### ISSUE THREAD

**Issue by hastingscj999** [sveinbjornt/Platypus#79]
Hi, I am trying to maintain the colors for the installer icon as I am using a branded asset, but once I select "create", the resulting installer icon is almost always a different color and the background renders as transparent, even if I use a .jpg image.

**Comment by hastingscj999** [comment]
I worked around the problem by using an online .jpg/.png to .icns converter, but it might be worth mentioning in the documentation that just dragging a .jpg or .png into the icon bucket will result in altered colors and backgrounds

**Comment by sveinbjornt** [comment]
A good point, thank you for pointing this out. Icon creation is handled by the open source IconFamily class in Platypus. As the documentation notes:

    Please note that having Platypus create the icon from an image file will typically not result in an icon that looks good in smaller sizes. For best results, use professional Mac OS X icon-editing software and specify a carefully crafted .icns file using the Select .icns file option.

**Comment by hastingscj999** [comment]
my mistake for missing that. thanks
