### ISSUE TITLE
error:  "Unrecognized character \xCA; marked by <-- HERE after <-- HERE near column 1 at /usr/bin/perl line 1." 

### ISSUE THREAD

**Issue by westmj** [sveinbjornt/Platypus#80]
I get an error like : "Unrecognized character \xCA; marked by <-- HERE after <-- HERE near column 1 at /usr/bin/perl line 1." 

I have a Hello, World!

#! /Users/westmj/perl5/perlbrew/perls/perl-5.16.0/bin/perl
print "Hello, World!\n";

which whether I set up with system perl or my local perlbrew gives the same sort of error.

I get "Unrecognized character \xCA; marked by <-- HERE after <-- HERE near column 1 at /usr/bin/perl line 1."  or "Unrecognized character \xCF; marked by <-- HERE after <-- HERE near column 1 at /Users/westmj/perl5/perlbrew/perls/perl-5.16.0/bin/perl line 1." depending how I set things up.

These are files from PC/Linux; is this a return character issue?  How would I fix that?

/Users/westmj/perl5/perlbrew/perls/perl-5.16.0/bin/perl is my perlbrew perl.

Any ideas?

Thanks for the great idea for a tool.

**Comment by sveinbjornt** [comment]
The \xCA is an invisible non-breaking space character which the Perl interpreter isn't happy about. Try opening the script with a good text editor and have it show invisible characters. Then you should be able to see the non-breaking spaces and remove them.

http://use.perl.org/use.perl.org/comments9812-3.html?sid=18447&cid=28408

**Comment by westmj** [comment]
Just to close loop, this appears to be due to using Macintosh line endings rather than Unix line endings.  My text editor allows this, and I was not taking into account that this is OSX not classic Mac.
