### ISSUE TITLE
Feature Request: Relative path for profiles

### ISSUE THREAD

**Issue by arvindsree** [sveinbjornt/Platypus#83]
It would be nice to have relative paths for scripts, icons and resources. It can be relative to the .platypus profile file.

**Comment by sveinbjornt** [comment]
Do you have in mind that Platypus would *generate* profiles with relative paths, or that parsing a .profile file would understand relative paths?  The former seems like a bad idea, whereas the latter is a good idea.

**Comment by arvindsree** [comment]
For the former I suggest giving an option if the user prefers relative paths.

**Comment by arvindsree** [comment]
But the latter in itself would bring up the functionality. The former can be of lower priority

**Comment by sveinbjornt** [comment]
Platypus now understands relative paths in profiles, but does not *generate* relative paths. I think that's a good solution. That way, those who want to use relative paths can manually edit the values in the Profile XML and have Platypus understand them.

**Comment by arvindsree** [comment]
Fair enough 👍

**Comment by yegortimoshenko** [comment]
@sveinbjornt Could you please add relative path support to `BundledFiles` as well?

**Comment by sveinbjornt** [comment]
Whoops, thought I already had. Now fixed in master.

**Comment by yegortimoshenko** [comment]
@sveinbjornt Cool! Now I can distribute Platypus profile along with the source code and collaborate with others in GitHub repos and such. Thank you so much :-)
