### ISSUE TITLE
-f not copying bundled files in platypus 5.1?

### ISSUE THREAD

**Issue by uglygus** [sveinbjornt/Platypus#85]
Mac OSX 10.10.5
platypus 4.9(working) vs 5.1(not) 

platypus 5.1 does not bundle files under my setup. The output does not list them as being copied and they do not show up in the of the finished app.

This is a freshly installed copy of Platypus 5.1. Installed in to Applications and then the command line app installed through the GUI. I only have 4.9 on this machine (command line only) as a test since 5.1 failed.

**V5.1 does not copy the bundled files**

$/usr/local/bin/platypus -v
platypus version 5.1

$/usr/local/bin/platypus -i '/Applications/Platypus.app/Contents/Resources/PlatypusDefault.icns'  -a 'Res-Copy-Test'  -o 'Text Window'  -p '/bin/sh'  -f './test.txt' -y  './Res-Copy-Test.sh' './Res-Copy-Test.app'
Overwriting app at path /Users/tbatters/Desktop/Res-Copy-Test/Res-Copy-Test.app
Creating application bundle folder hierarchy
Copying executable to bundle
Copying nib file to bundle
Copying script
Creating AppSettings property list
Writing application icon
Writing Info.plist
Moving app to destination directory '/Users/tbatters/Desktop/Res-Copy-Test/Res-Copy-Test.app'
Registering with Launch Services
Done

**V4.9 copies the bundled files**

$/Users/tbatters/Desktop/platypus -v
platypus version 4.9 by Sveinbjorn Thordarson

$~/Desktop/platypus -i '/Applications/Platypus.app/Contents/Resources/PlatypusDefault.icns'  -a 'Res-Copy-Test'  -o 'Text Window'  -p '/bin/sh'  -f './test.txt' -y  './Res-Copy-Test.sh' './Res-Copy-Test.app'
Overwriting app at path /Users/tbatters/Desktop/Res-Copy-Test/Res-Copy-Test.app
Creating app bundle hierarchy
Copying executable to bundle
Copying nib file to bundle
Copying script
Creating property lists
Writing application icon
Creating Info.plist
Writing Info.plist
Copying bundled files
Copying "test.txt" to bundle
Moving app to destination
Done

**Comment by sveinbjornt** [comment]
Thanks for your feedback. This bug has been fixed on the current master branch and will be released with 5.2, which should be out soon.
