### ISSUE TITLE
Feature Request: closable droplet window

### ISSUE THREAD

**Issue by phloggu** [sveinbjornt/Platypus#86]
A nice feature for a Droplet-Interface-App would be to make the droplet window closable. In the "Edit Drop Settings" there should appear a new tickable menu item: "Enable closing the droplet window quits your application". A droplet application with this setting would have the red closing button in the droplet window enabled. Pressing that red button would quit the application, like "⌘Q".

Up to now the red closing button is always disabled.

**Comment by sveinbjornt** [comment]
What you are asking for is non-standard Mac OS X app behaviour. OS X apps generally don't quit when their windows are closed.

**Comment by phloggu** [comment]
... except System Preferences, Disk Utility, Contacts, Activity Monitor, Calculator, AirPort Utility, Digital Color Meter, Network Utility, ODBC Manager, Screen Sharing, System Information, Reminders, Notes and some others. For smaller Utilities it seems quite common and I think this is what Platypus is just made for.

**Comment by sveinbjornt** [comment]
Fair enough. I decided against making minor behaviour like this *yet another option* so now all droplet apps quit when window is closed. Now in latest master.
