### ISSUE TITLE
Version isnt saved correctly into the profile

### ISSUE THREAD

**Issue by arvindsree** [sveinbjornt/Platypus#90]
Minor bug where the version information is lost when saved into the profile.

To reproduce: Change version to 1.1 and save the profile. Close platypus and open the platypus file again. The version is shown as 1.0

**Comment by sveinbjornt** [comment]
Can't replicate in master or in the 5.1 release.  Are you sure it isn't just an issue of ending the editing session in the Version text field before saving the profile?

**Comment by sveinbjornt** [comment]
Still haven't been able to replicate. This is almost certainly due to not ending the editing session in the text field before choosing Save Profile.

**Comment by arvindsree** [comment]
Looks like I am not able to reproduce it as well.  Will re-open it if I do. Thanks
