### ISSUE TITLE
Can I run a script before Log Out or Shutdown?

### ISSUE THREAD

**Issue by staminna** [sveinbjornt/Platypus#91]
Hi

Thanks for the app, seems very nice though I'm not very familiar with launchd .org files.
Can Platypus run a script before Log Out or Shutdown?

Thanks

**Comment by sveinbjornt** [comment]
That's not really what Platypus is intended for. Platypus creates GUI applications from scripts. If you want a script to run at logout or shutdown, you don't want a GUI. Although you can of course add a Platypus-generated app to Login Items.
