### ISSUE TITLE
Get stdout when running a process in a ruby script.

### ISSUE THREAD

**Issue by dwkns** [sveinbjornt/Platypus#92]
I have a ruby script which in turn needs to run a system process (ffmpeg) and capture the output (progress of the compression) in realtime. 

It works as expected in the terminal if its run as `ruby myflie.rb` the output is captured and printed.

However the exact same script within Platypus prints out the first line to stderr, then hangs until the ffmpeg process has finished and then prints out all the progress lines. 

```
#!/usr/bin/ruby
require 'open3'
cmd = "/usr/local/bin/ffmpeg in.mkv out.mp4"

Open3.popen3(cmd) do |stdin, stdout, stderr, thread|
    stderr.each("\r") do |line|
      puts "stderr is : #{line}"
    end 
end
```

Is this expected behaviour? A bug? Is there a workaround?

**Comment by sveinbjornt** [comment]
Expected behaviour. Platypus apps are not terminals, and don't process the text output from the script. Carriage returns ("\r") don't work but you'll find that newlines do.
