### ISSUE TITLE
excessive output on stderr and stdout can burden the console window

### ISSUE THREAD

**Issue by jbfaden** [sveinbjornt/Platypus#93]
We found we had to turn off the console window because our app may print lots of text to the stderr and stdout channels, and the GUI generated by Platypus could not keep up, resulting in very slow performance of the app.

We work-around this by disabling the console window.  This is not really a problem for us, but I wanted to let you know.

This could probably be demonstrated by writing a small program that loops, sending lots of text to stdout.  This can also be demonstrated with our app (Autoplot), using the following procedure:

To demo the bug, see http://autoplot.org/data/build/mac/Autoplot-v2016a_8.dmg which shows the problem.  You should enable the Autoplot console tab and the script tab ([Menubar]->Options->Enable Feature), and then run the script:

`for i in xrange(100000):
   print 'some text %d' % i`

This will run properly if the console tab is running and text is not sent to stdout.
Now disable the Autoplot console tab, stop the app, and restart it.  Run the same script, and it will take minutes instead of seconds to finish and performance will be sluggish while it is running.

**Comment by sveinbjornt** [comment]
Yeah, this is probably an issue with NSTextView, which doesn't seem to handle lots of text all that well. Either find a faster way of showing the output text, or simply delete pre-existing content in the text view and start afresh after a while.

**Comment by jbfaden** [comment]
That's the sort of thing we do with our software, have a AWT Timer that copies over the last message into the GUI, and then another thread that is reading the stdout/stderr channels to keep track of the last message.

**Comment by sveinbjornt** [comment]
OK, this is now fixed in master and will make it into the 5.2 release. It now takes 7-8 seconds to print 100k lines of text and the program doesn't freeze up, at least on my system.
