### ISSUE TITLE
App Works Launched from Command Line But Not When Double-Clicked

### ISSUE THREAD

**Issue by madranet** [sveinbjornt/Platypus#95]
I'm just dipping my toes in the water with Platypus and trying to put together an app which edits the `/etc/hosts` file. Code is given below.

My problem is that, when I run the app bundle directly from the command line:

`/Users/madra/claraithe/python/Prevvo/Prevvo.app/Contents/MacOS/Prevvo`

it works perfectly; backs up the existing `etc/hosts` file, writes the new one and shows the appropriate notifications.

However, if I launch the app the conventional way, by double-clicking it in the Finder, nothing seems to happen. Well, I get the dialogue to enter my admin password [obviously, the app requires root privileges] but after that no further output. I don't get any error messages, but the existing `/etc/hosts` file isn't backed up and nothing is written to it either.

Ironically, it was for this reason that I launched the app via the command line in the first place:

`/Users/madra/claraithe/python/Prevvo/Prevvo.app/Contents/MacOS/Prevvo`

as I was hoping to get some useful debugging info in my terminal. But, the app runs perfectly when launched that way. So I'm a bit stuck as to how I go about troubleshooting this.

Here's the code I've got so far. As it's very initial stages, please forgive the clunkiness!

```python
#!/usr/bin/env python3

#import modules
import sys
import logging
from logging.handlers import SysLogHandler
from shutil import copyfile

#setup logging
logger = logging.getLogger("Prevvo")
logger.setLevel(logging.DEBUG)
syslog = SysLogHandler(address ="/var/run/syslog")
formatter = logging.Formatter("%(name)s: %(levelname)s %(message)s")
syslog.setFormatter(formatter)
logger.addHandler(syslog)

#test log messages
#logger.debug('this is debug')
#logger.critical('this is critical')

#source and destination hosts file & backup
source = "/etc/hosts"
destination = "/etc/hosts-prevvo-backup"

#banlist file [hard-wired for now]
banlist = open("/Users/madra/claraithe/python/Prevvo/banlist.txt")

#backup existing hosts file
try:
	if copyfile(source, destination):
            logger.info("hosts file backed up")
            print("NOTIFICATION:Hosts file backed up\n")

#permissions error
except PermissionError:
    logger.critical("Permissions error backing up existing hosts file. Are you admin?")
    print("Permissions error backing up existing hosts file. Are you admin?\n")

#misc. error
except:
    logger.critical("Unknown error")
    print("Unknown error")

#open hosts file
try:
	with open(source, "a") as hostfile:
            #append start of prevvo block
            hostfile.write("\n### PREVVO BLOCKLIST ###\n")
            #append normal and www version for each line in banlist
            for line in banlist.readlines():
                hostfile.write("127.0.0.1\t{0}".format(line))
                hostfile.write("127.0.0.1\twww.{0}".format(line))
            #append end of prevvo block 
            hostfile.write("### END PREVVO BLOCKLIST ###\n")
            logger.info("New hosts file written")
            print("NOTIFICATION:Wrote new hosts file\n")

#permissions error
except PermissionError:
    logger.critical("Permissions error writing hosts file. Are you admin?")
    print("Permissions error writing hosts file. Are you admin?")

#misc error
except:
    logger.critical("Unknown error")
    print("Unknown error")
```

**Comment by sveinbjornt** [comment]
Are you relying on environment variables or other shell-specific features? You could try to wrap the invocation of the python script in a bash script. Try to run it through Platypus via /bin/bash -l and see if it works.

**Comment by madranet** [comment]
The only environment related thing I can think of is that I've got a shebang at the top of the Python script, to use Python3 instead of the default system Python [2,7] `#!/usr/bin/env python3`.  Other than that, it's a pretty straightforward script. It writes to `/etct/hosts` which requires `sudo`, but that should be covered by Platypus's 'require Root prveleges', shouldn't it?

**Comment by sveinbjornt** [comment]
Ah, so you're running it through /usr/bin/env ... try setting the interpreter as your python3 path see whether that changes anything.

**Comment by madranet** [comment]
Ah. I've solved the mystery.  

I tried various options for the shebang, including `#!/usr/bin/env python3` `#!/usr/bin/python3`, `#!/usr/local/bin/python3` and no shebang --none of which made any difference.  Then, I wondered if the Python script should be made executable.  So I did a `chmod +x` on it and tried again and it worked perfectly.

![2017-04-25_18-31-49](https://cloud.githubusercontent.com/assets/669658/25398894/7f05202c-29e5-11e7-938a-52ac4ad9803e.png)

Apologies if this was mentioned in the docs, but [as ever] I decided to tinker first and RTFM afterwards. 

Cheers for your help!.

**Comment by madranet** [comment]
Just to [sort of] close this:

I reconfigured my Platypus settings to use the default system Python, rather than trying to induce it to use Python3 and it worked fine. So obviously the problem lies in not using the system Python. 

No biggie. I'll just rejigger the script a bit if needs be to use Python, rather than Python3 syntax.
