### ISSUE TITLE
STPrivilegedTask not working when invoking bash

### ISSUE THREAD

**Issue by sveinbjornt** [sveinbjornt/Platypus#97]
STPrivilegedTask works if interpreter is /bin/sh but not /bin/bash. 

    

> But it seems that with a script written in bash, platypus doesn’t  run the script with root privileges.
> 
> We had a script, written in sh, which has the root level, everything’s fine in Platypus. 
> 
> We wanted to do do the same with a script written in bash. But we have seen that in Platypus, the script has the right of the user, not the rights of root.
> 
> Is it normal?

**Comment by ernestasen** [comment]
I ran in to this issue. Some of the scripts we need to run are written in bash and I noticed that Platypus fails on those scripts.

What's the status with this issue? Is there any plans to fix that? Or maybe there is some workaround for that?

**Comment by sveinbjornt** [comment]
Truth be told, I have no idea what's causing this. /bin/sh is a bash binary (bash being the default shell on macOS), but it's *different* from /bin/bash. Why? Your guess is as good as mine.

See the following:

<img width="526" alt="screen shot 2018-03-15 at 18 19 26" src="https://user-images.githubusercontent.com/654045/37479721-9999eb56-287d-11e8-8a93-e63d10d8848b.png">

**Comment by hstriepe** [comment]
Just checked to make sure, this is not an issue with the OS. At least sh & bash have not changed since El Capitan. -v3.2.57

**Comment by hstriepe** [comment]
Ok, found the following:
1. Changing the scripts to sh fixed the issue
2. Minor errors unnoticed in running from shell (e.g. the script continues) seems to abort the script in Platypus. You need to do verbose checking and error trapping to track this down

#! /bin/bash clearly cannot run as root.

**Comment by mirkop** [comment]
I know that this is an old issue, but it would help note this known issue in the documentation.

> Special Options
> 
> Run with root privileges: If selected, the application prompts for an Administrator password and executes the script with escalated privileges via Apple's Security Framework. This is not strictly equivalent to running the script as the root user. For details, see the documentation for Apple's Security Framework.
> 
> Platypus scripts must not use the 'sudo' command. This causes the script to prompt for input via STDIN, and since no input is forthcoming, the application will hang indefinitely.
> 
> Please note that if this option is selected, the script will not print STDERR output due to limitations in the Security APIs. This can be circumvented by using a shell script to execute another script while piping STDERR into STDOUT (e.g. perl myScript.pl 2>&1).
> 
> Known issue: /bin/bash scripts cannot run with root privileges.

**Comment by sveinbjornt** [comment]
@mirkop Done.
