### ISSUE TITLE
Script not running from .app, but in terminal works

### ISSUE THREAD

**Issue by derchrisuk** [sveinbjornt/Platypus#98]
Hi,

since a few days I'm trying to package a Python script into an .app
Tried several tools already, PyInstaller, Py2App, cx_freeze.
None was working as it should.
Found Platypus, and gave it a try.
But it seem to be messing up at some pint as well.
Basically in my Profile I have set the Script Type to `Other`, and path to `/usr/local/bin/python3`
Set the correct Script path, and folders to be copied over to the resource folder.
Running the script in terminal works fine.
But running the resulting .app does not, and gives me some weird Python errors.
Running the resulting Mach App in `MacOS` folder from terminal works as well.
So I don't know what is happening here.
To me it looks like some kind of ENV is being used/missing when running the .app
I'm out of ideas.

**Comment by sveinbjornt** [comment]
Platypus apps do not inherit the user's shell environment. You can get that effect by invoking bash -l and running your python command in a bash script. My guess is you're depending on something in ENV

**Comment by derchrisuk** [comment]
Yes I believe I had to set 2x ENV variables.
Is there a chance Platypus can be configured to set ENV for specific values ?

**Comment by sveinbjornt** [comment]
You can just set the required ENV variables in your script.
