### ISSUE TITLE
VirusTotal detecting packages made with Platypus as infected

### ISSUE THREAD

**Issue by akshayaurora** [sveinbjornt/Platypus#99]
https://virustotal.com/en/file/0ca63310d0fc2a0e708688c280d9b683155a2edb3c51be44e3e6c1fb6fe2c31a/analysis/1496745070/

False positive? This effects every package made with Platypus.
I even tested just uploading using url directly from platypus website, making sure my own system was not involved in between.

**Comment by sveinbjornt** [comment]
Yeah, definitely false positive. Curiously, it has no issue with http://sveinbjorn.org/files/software/platypus.zip but doesn't like it when I upload a zipped Platypus.app.
